/* SPDX-License-Identifier: AGPL-3.0-only
 * Generated by luminal-vgd-ffi's build.rs (cbindgen) — do not edit.
 *
 * Link (MSYS2 UCRT64):
 *   cargo build -p luminal-vgd-ffi --release --target x86_64-pc-windows-gnullvm
 *   ... -lluminal_vgd_ffi -lcfgmgr32 -lws2_32 -luserenv -lntdll -lbcrypt
 */

#ifndef LUMINAL_VGD_H
#define LUMINAL_VGD_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * OS-level failure (I/O error, device unreachable) as opposed to a
 * negative proto `err::*` code from the driver.
 */
#define VGD_ERR_IO -1000

/**
 * Capability bits of `VgdCaps.caps` the backend gates on (literal
 * mirrors of proto `caps::*`; the asserts below keep them honest —
 * cbindgen cannot evaluate cross-crate constants).
 */
#define VGD_CAP_HDR10 1

#define VGD_CAP_SDR10_BIT 4

#define VGD_CAP_HW_CURSOR 32

/**
 * The driver implements [`vgd_update_modes`] (proto 0.5, driver build
 * 17+). Absent ⇒ a monitor's mode list is fixed at create time and the
 * caller must advertise everything it may need up front.
 */
#define VGD_CAP_DYNAMIC_MODES 512

#define VGD_CAP_D3D12_FENCE_TRANSPORT 1024

#define VGD_CAP_FENCE_TRANSPORT_REQUIRED 2048

#define VGD_CREATE_D3D12_FENCE_TRANSPORT 4

#define VGD_CREATE_FENCE_TRANSPORT_REQUIRED 8

/**
 * `VgdCursorShape.kind` values (mirror proto `cursor_kind::*`).
 */
#define VGD_CURSOR_KIND_ALPHA 1

#define VGD_CURSOR_KIND_MASKED 3

/**
 * Worst-case shape buffer size for `vgd_cursor_shape` (256² 32bpp).
 */
#define VGD_CURSOR_SHAPE_BUFFER_SIZE ((256 * 256) * 4)

/**
 * [`VgdUpdateModesReply::first_rejected`] when nothing was rejected.
 * Distinct from index 0, which is a real rejection of the first mode.
 */
#define VGD_NO_REJECTED_INDEX UINT32_MAX

/**
 * [`VgdUpdateModesReply::flags`]: the list is not in force yet — the
 * driver queued the OS-side push, which cannot have run before this call
 * returned. A push that fails or is deferred leaves the PREVIOUS list in
 * force and the request fully retryable (resending it really does push
 * again), and surfaces as the monitor's sticky `last_error` (`-13`) in
 * the status reply.
 */
#define VGD_UPDATE_PENDING 1

/**
 * [`VgdUpdateModesReply::flags`]: fewer modes accepted than requested,
 * because some requested modes are not in the monitor's create-time list
 * and can never be offered. Success with detail — everything that exists
 * was published. See [`VgdUpdateModesReply::rejected`].
 */
#define VGD_UPDATE_PARTIAL 2

/**
 * [`VgdUpdateModesReply::flags`]: **the request was refused permanently —
 * do not retry it.** The list would have taken away the mode the OS is
 * currently running on this display, which would force a mode change on a
 * live monitor mid-stream, so the driver refused the push and left the
 * previously offered list in force (`result` = `-14`).
 *
 * Retrying is the one response that cannot work: the answer depends on
 * what the display is running, not on the attempt. Read
 * [`VgdUpdateModesReply::blocking_mode`] and either include that mode in
 * the next request or change the display mode first.
 */
#define VGD_UPDATE_BLOCKED 4

/**
 * [`VgdUpdateModesReply::blocking_mode`] when nothing is blocking.
 * Distinct from index 0, which names the monitor's first create-time mode.
 */
#define VGD_NO_MODE_INDEX UINT32_MAX

typedef struct VgdCursorHandle VgdCursorHandle;

typedef struct VgdDeviceHandle VgdDeviceHandle;

typedef struct VgdRingHandle VgdRingHandle;

/**
 * Handshake results the backend needs for capability gating.
 */
typedef struct VgdCaps {
  uint16_t proto_major;
  uint16_t proto_minor;
  uint32_t driver_build;
  uint32_t caps;
  uint32_t max_monitors;
  uint32_t watchdog_secs;
} VgdCaps;

/**
 * One display mode; `modes[0]` is preferred. Mirrors proto `ModeSpec`.
 */
typedef struct VgdModeSpec {
  uint32_t width;
  uint32_t height;
  uint32_t refresh_millihz;
} VgdModeSpec;

/**
 * Monitor creation parameters (see proto `CreateMonitorRequest` for full
 * field semantics; zero means "driver default" where the proto says so).
 */
typedef struct VgdCreateRequest {
  uint64_t session_id;
  uint64_t display_id;
  uint64_t adapter_luid;
  uint32_t lease_timeout_ms;
  uint32_t bit_depth;
  uint32_t hdr;
  uint32_t flags;
  uint32_t mode_count;
  struct VgdModeSpec modes[4];
  uint32_t physical_width_mm;
  uint32_t physical_height_mm;
  /**
   * NUL-padded UTF-16LE.
   */
  uint16_t friendly_name[32];
  /**
   * Desired HDR peak luminance in nits for the monitor EDID's
   * CTA-861.3 block. 0 = driver default (≈993 nits). Ignored for SDR
   * monitors and by pre-0.4 drivers (proto 0.4 additive field).
   */
  uint32_t max_nits;
} VgdCreateRequest;

typedef struct VgdCreateReply {
  uint64_t session_id;
  uint64_t display_id;
  /**
   * `0` or a negative proto `err::*` code.
   */
  int32_t result;
  uint32_t ring_slots;
  uint32_t connector_index;
} VgdCreateReply;

/**
 * Parameters for [`vgd_update_modes`] (mirrors proto
 * `UpdateModesRequest`).
 */
typedef struct VgdUpdateModesRequest {
  uint64_t session_id;
  /**
   * Reserved; pass 0.
   */
  uint32_t flags;
  /**
   * Valid entries in `modes` (1..=4). Zero is refused — the offered
   * list can be replaced, never emptied.
   */
  uint32_t mode_count;
  /**
   * The complete set of modes the monitor should offer from now on.
   * Every entry must be one the monitor was CREATED with.
   */
  struct VgdModeSpec modes[4];
} VgdUpdateModesRequest;

typedef struct VgdUpdateModesReply {
  uint64_t session_id;
  /**
   * `0` (accepted) or a negative proto `err::*` code.
   */
  int32_t result;
  /**
   * Modes the monitor offers once this request is applied.
   */
  uint32_t mode_count;
  /**
   * Requested modes the driver published. `accepted < requested` means
   * the rest are modes this monitor was not created with and can never
   * offer: partial application, NOT an error, and nothing that existed
   * was discarded.
   */
  uint32_t accepted;
  /**
   * Echo of the request's `mode_count`.
   */
  uint32_t requested;
  /**
   * `VGD_UPDATE_PENDING` / `VGD_UPDATE_PARTIAL`.
   */
  uint32_t flags;
  /**
   * Requested modes with no counterpart in the monitor's create-time
   * list. `accepted + rejected == requested` always.
   */
  uint32_t rejected;
  /**
   * Index into `modes` of the first rejected entry, or
   * [`VGD_NO_REJECTED_INDEX`] — so a caller can name the mode it
   * cannot have instead of only counting it.
   */
  uint32_t first_rejected;
  /**
   * With [`VGD_UPDATE_BLOCKED`] set: index into the mode list this
   * monitor was CREATED with, naming the mode the OS is currently
   * running and that this request would have taken away. Otherwise
   * [`VGD_NO_MODE_INDEX`].
   *
   * This is the one field that turns "no" into something actionable:
   * ask again with a subset that KEEPS this mode, or move the display
   * onto the mode you want first and gate afterwards.
   */
  uint32_t blocking_mode;
} VgdUpdateModesReply;

/**
 * Snapshot of the ring header for health/fallback decisions.
 */
typedef struct VgdRingStatus {
  uint32_t generation;
  /**
   * proto `ring_state::*` (1 ACTIVE, 2 REBUILDING, 3 DEAD, 0 uninit).
   */
  uint32_t state;
  /**
   * Transport flags actually selected for this generation.
   */
  uint32_t transport_flags;
  uint32_t reserved;
  uint64_t latest_sequence;
  uint64_t frames_published;
  uint64_t frames_dropped;
  uint64_t heartbeat_qpc;
  uint64_t qpc_frequency;
} VgdRingStatus;

/**
 * A claimed (checked-out) frame. The driver will not overwrite this slot
 * until `vgd_ring_release`.
 */
typedef struct VgdFrame {
  uint32_t index;
  /**
   * Bake into the texture name; re-claim if the header generation has
   * moved on by the time the texture is opened.
   */
  uint32_t generation;
  uint64_t sequence;
  uint64_t present_qpc;
  uint64_t ready_fence_value;
} VgdFrame;

/**
 * Cursor position/visibility snapshot (`vgd_cursor_state`).
 */
typedef struct VgdCursorState {
  /**
   * Desktop coordinates of the shape's top-left pixel (can be
   * negative when the hotspot hangs off the display edge).
   */
  int32_t x;
  int32_t y;
  /**
   * 0 hidden, 1 visible.
   */
  uint32_t visible;
  /**
   * Even counter bumped after each complete shape rewrite (0 = no
   * shape yet). Re-fetch the shape when it changes.
   */
  uint32_t shape_generation;
  uint64_t position_qpc;
} VgdCursorState;

/**
 * Cursor shape metadata; pixels land in the caller's buffer at a
 * `width * 4` pitch (32bpp, `VGD_CURSOR_KIND_*`).
 */
typedef struct VgdCursorShape {
  uint32_t kind;
  uint32_t width;
  uint32_t height;
  uint32_t hotspot_x;
  uint32_t hotspot_y;
  /**
   * The generation this copy is valid for.
   */
  uint32_t generation;
} VgdCursorShape;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Win32 error code of the most recent failing FFI call on the calling
 * thread (0 = none recorded). Read it immediately after a NULL /
 * [`VGD_ERR_IO`] return; success does not clear it.
 */
uint32_t vgd_last_error(void);

/**
 * Open the LuminalVGD control device. NULL when the driver is absent —
 * the caller falls back to another backend.
 */
struct VgdDeviceHandle *vgd_device_open(void);

void vgd_device_close(struct VgdDeviceHandle *dev);

int32_t vgd_handshake(struct VgdDeviceHandle *dev, struct VgdCaps *out);

int32_t vgd_create_monitor(struct VgdDeviceHandle *dev,
                           const struct VgdCreateRequest *req,
                           struct VgdCreateReply *out);

/**
 * Change WHICH of a LIVE monitor's create-time modes it currently
 * offers — no destroy/create cycle, so no `DBT_DEVNODES_CHANGED`
 * broadcast and no monitor churn (proto 0.5, driver build 17+).
 *
 * The motivating case: a client streams a display whose create call
 * listed both its base refresh rate and the frame-generation-doubled
 * one, and only then launches a framegen title. Calling this with
 * `{doubled}` makes the doubled rate the one on offer, and calling it
 * again with `{base, doubled}` (or `{base}`) puts things back.
 *
 * # Contract the caller must honor
 *
 * - **Gate on `VgdCaps.caps & VGD_CAP_DYNAMIC_MODES`.** Against an older
 *   driver the opcode is unknown and this returns [`VGD_ERR_IO`]; that
 *   is safe (never a false success) but it is a wasted round trip, and
 *   the log line the caller writes should name the driver's version.
 * - **You can only choose among the modes you CREATED the monitor
 *   with.** A monitor's description is frozen at creation — no IddCx DDI
 *   replaces it on a live monitor, and Windows only offers modes that
 *   are in BOTH the description and the pushed list — so a mode that was
 *   not in `vgd_create_monitor`'s list is rejected here
 *   (`VGD_UPDATE_PARTIAL`, or `result` = `-3` if nothing requested
 *   exists). Create with every mode you might later want.
 * - **The list is replaced, never emptied.** `mode_count == 0` is
 *   refused; so is a request in which every mode is unknown to the
 *   monitor. In both cases the previously offered list stays in force.
 * - **Degrade, never refuse.** Treat both `VGD_ERR_IO` and any negative
 *   `result` as "the offered modes are unchanged, carry on with the
 *   session". A failed update is never a reason to tear a stream down.
 * - **Do not retry a [`VGD_UPDATE_BLOCKED`] refusal** (`result` = `-14`).
 *   Every other failure here leaves the previous list in force and really
 *   does push again on the next attempt, so retrying is reasonable. This
 *   one is a statement about the mode the display is RUNNING: the driver
 *   refused to take that mode away mid-stream, and will refuse again until
 *   the display is on something else. `blocking_mode` indexes your own
 *   `vgd_create_monitor` list and names it — either include that mode in
 *   the next request, or change the display mode yourself first (the
 *   modeset is then yours, at a moment you chose) and gate afterwards.
 * - **`result == 0` means ACCEPTED, not applied.** The driver completes
 *   the request before it calls the OS. The applied/failed outcome shows
 *   up in ETW and as the monitor's sticky `last_error` in the status
 *   reply. `result == 0` with neither flag set is the only shape that
 *   means "every mode you asked for is offered right now"; with
 *   `VGD_UPDATE_PENDING` set, an update is still outstanding, and if it
 *   does not land the previous list stays in force and this exact
 *   request can simply be sent again.
 * - **Check `accepted` against `requested`**, and read `rejected` /
 *   `first_rejected` when they differ: that names a mode this monitor
 *   will never offer, which is a create-time problem, not a retryable
 *   one.
 */
int32_t vgd_update_modes(struct VgdDeviceHandle *dev,
                         const struct VgdUpdateModesRequest *req,
                         struct VgdUpdateModesReply *out);

int32_t vgd_destroy_monitor(struct VgdDeviceHandle *dev, uint64_t session_id);

/**
 * Feed the per-lease watchdog; call at least once per `watchdog_secs`.
 */
int32_t vgd_ping(struct VgdDeviceHandle *dev, uint64_t session_id);

/**
 * Map the frame ring for a created monitor. NULL until the driver has
 * created the section (retry briefly after create).
 */
struct VgdRingHandle *vgd_ring_open(uint64_t session_id, uint32_t ring_slots);

void vgd_ring_close(struct VgdRingHandle *ring);

int32_t vgd_ring_status(struct VgdRingHandle *ring, struct VgdRingStatus *out);

/**
 * Claim the freshest published frame. Returns `true` and fills `out`
 * when a frame was checked out; `false` when nothing is published.
 */
bool vgd_ring_claim(struct VgdRingHandle *ring, struct VgdFrame *out);

/**
 * Release a claimed frame back to the driver. Exactly once per claim.
 */
void vgd_ring_release(struct VgdRingHandle *ring, uint32_t index);

/**
 * Map the shared cursor section for a created monitor (requires
 * `VGD_CAP_HW_CURSOR`). NULL when the driver has no cursor plane for
 * this monitor — the cursor is then composed into frames as before.
 */
struct VgdCursorHandle *vgd_cursor_open(uint64_t session_id);

void vgd_cursor_close(struct VgdCursorHandle *cursor);

/**
 * Position/visibility snapshot (cheap; poll every frame).
 */
int32_t vgd_cursor_state(struct VgdCursorHandle *cursor, struct VgdCursorState *out);

/**
 * Copy the current shape into `buf` (`buf_len` ≥ width*height*4; size
 * `VGD_CURSOR_SHAPE_BUFFER_SIZE` always suffices). Returns `true` and
 * fills `out` on a consistent copy; `false` when no shape is published
 * yet or the driver was mid-rewrite (retry next frame).
 */
bool vgd_cursor_shape(struct VgdCursorHandle *cursor,
                      uint8_t *buf,
                      uint32_t buf_len,
                      struct VgdCursorShape *out);

/**
 * Compose the named shared-texture name for (session, generation, slot)
 * into `out` (capacity 96 u16s, NUL-padded). Returns the char count.
 * Open with `ID3D11Device1::OpenSharedResourceByName`.
 */
uint32_t vgd_slot_texture_name(uint64_t session_id,
                               uint32_t generation,
                               uint32_t slot,
                               uint16_t *out);

/**
 * Compose the D3D12-openable shared texture name for a claimed slot.
 */
uint32_t vgd_slot_texture_d3d12_name(uint64_t session_id,
                                     uint32_t generation,
                                     uint32_t slot,
                                     uint16_t *out);

/**
 * Compose the shared producer timeline-fence name for a ring generation.
 */
uint32_t vgd_ring_fence_name(uint64_t session_id, uint32_t generation, uint16_t *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LUMINAL_VGD_H */
