/* SPDX-License-Identifier: AGPL-3.0-only
 * Generated by luminal-vgd-ffi's build.rs (cbindgen) — do not edit.
 *
 * Link (MSYS2 UCRT64):
 *   cargo build -p luminal-vgd-ffi --release --target x86_64-pc-windows-gnullvm
 *   ... -lluminal_vgd_ffi -lcfgmgr32 -lws2_32 -luserenv -lntdll -lbcrypt
 */

#ifndef LUMINAL_VGD_H
#define LUMINAL_VGD_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * OS-level failure (I/O error, device unreachable) as opposed to a
 * negative proto `err::*` code from the driver.
 */
#define VGD_ERR_IO -1000

/**
 * Capability bits of `VgdCaps.caps` the backend gates on (literal
 * mirrors of proto `caps::*`; the asserts below keep them honest —
 * cbindgen cannot evaluate cross-crate constants).
 */
#define VGD_CAP_HDR10 1

#define VGD_CAP_SDR10_BIT 4

#define VGD_CAP_HW_CURSOR 32

/**
 * The driver implements [`vgd_update_modes`] (proto 0.5, driver build
 * 17+). Absent ⇒ a monitor's mode list is fixed at create time and the
 * caller must advertise everything it may need up front.
 */
#define VGD_CAP_DYNAMIC_MODES 512

/**
 * `VgdCursorShape.kind` values (mirror proto `cursor_kind::*`).
 */
#define VGD_CURSOR_KIND_ALPHA 1

#define VGD_CURSOR_KIND_MASKED 3

/**
 * Worst-case shape buffer size for `vgd_cursor_shape` (256² 32bpp).
 */
#define VGD_CURSOR_SHAPE_BUFFER_SIZE ((256 * 256) * 4)

/**
 * [`VgdUpdateModesReply::flags`]: the list is not in force yet — the
 * driver queued the OS-side push, which cannot have run before this call
 * returned. A push that fails or is deferred leaves the PREVIOUS list in
 * force and the request fully retryable (resending it really does push
 * again), and surfaces as the monitor's sticky `last_error` (`-13`) in
 * the status reply.
 */
#define VGD_UPDATE_PENDING 1

/**
 * [`VgdUpdateModesReply::flags`]: fewer modes accepted than requested,
 * because the monitor's list is at its cap. Success with detail — what
 * fit was applied and nothing was removed.
 */
#define VGD_UPDATE_PARTIAL 2

typedef struct VgdCursorHandle VgdCursorHandle;

typedef struct VgdDeviceHandle VgdDeviceHandle;

typedef struct VgdRingHandle VgdRingHandle;

/**
 * Handshake results the backend needs for capability gating.
 */
typedef struct VgdCaps {
  uint16_t proto_major;
  uint16_t proto_minor;
  uint32_t driver_build;
  uint32_t caps;
  uint32_t max_monitors;
  uint32_t watchdog_secs;
} VgdCaps;

/**
 * One display mode; `modes[0]` is preferred. Mirrors proto `ModeSpec`.
 */
typedef struct VgdModeSpec {
  uint32_t width;
  uint32_t height;
  uint32_t refresh_millihz;
} VgdModeSpec;

/**
 * Monitor creation parameters (see proto `CreateMonitorRequest` for full
 * field semantics; zero means "driver default" where the proto says so).
 */
typedef struct VgdCreateRequest {
  uint64_t session_id;
  uint64_t display_id;
  uint64_t adapter_luid;
  uint32_t lease_timeout_ms;
  uint32_t bit_depth;
  uint32_t hdr;
  uint32_t flags;
  uint32_t mode_count;
  struct VgdModeSpec modes[4];
  uint32_t physical_width_mm;
  uint32_t physical_height_mm;
  /**
   * NUL-padded UTF-16LE.
   */
  uint16_t friendly_name[32];
  /**
   * Desired HDR peak luminance in nits for the monitor EDID's
   * CTA-861.3 block. 0 = driver default (≈993 nits). Ignored for SDR
   * monitors and by pre-0.4 drivers (proto 0.4 additive field).
   */
  uint32_t max_nits;
} VgdCreateRequest;

typedef struct VgdCreateReply {
  uint64_t session_id;
  uint64_t display_id;
  /**
   * `0` or a negative proto `err::*` code.
   */
  int32_t result;
  uint32_t ring_slots;
  uint32_t connector_index;
} VgdCreateReply;

/**
 * Parameters for [`vgd_update_modes`] (mirrors proto
 * `UpdateModesRequest`).
 */
typedef struct VgdUpdateModesRequest {
  uint64_t session_id;
  /**
   * Reserved; pass 0.
   */
  uint32_t flags;
  /**
   * Valid entries in `modes` (1..=4).
   */
  uint32_t mode_count;
  struct VgdModeSpec modes[4];
} VgdUpdateModesRequest;

typedef struct VgdUpdateModesReply {
  uint64_t session_id;
  /**
   * `0` (accepted) or a negative proto `err::*` code.
   */
  int32_t result;
  /**
   * Modes the monitor advertises once this request is applied.
   */
  uint32_t mode_count;
  /**
   * Requested modes the driver took — appended now or already
   * advertised. `accepted < requested` means the monitor's list was at
   * its cap and the rest did not fit: partial application, NOT an
   * error, and nothing that fit was discarded.
   */
  uint32_t accepted;
  /**
   * Echo of the request's `mode_count`.
   */
  uint32_t requested;
  /**
   * `VGD_UPDATE_PENDING` / `VGD_UPDATE_PARTIAL`.
   */
  uint32_t flags;
} VgdUpdateModesReply;

/**
 * Snapshot of the ring header for health/fallback decisions.
 */
typedef struct VgdRingStatus {
  uint32_t generation;
  /**
   * proto `ring_state::*` (1 ACTIVE, 2 REBUILDING, 3 DEAD, 0 uninit).
   */
  uint32_t state;
  uint64_t latest_sequence;
  uint64_t frames_published;
  uint64_t frames_dropped;
  uint64_t heartbeat_qpc;
  uint64_t qpc_frequency;
} VgdRingStatus;

/**
 * A claimed (checked-out) frame. The driver will not overwrite this slot
 * until `vgd_ring_release`.
 */
typedef struct VgdFrame {
  uint32_t index;
  /**
   * Bake into the texture name; re-claim if the header generation has
   * moved on by the time the texture is opened.
   */
  uint32_t generation;
  uint64_t sequence;
  uint64_t present_qpc;
} VgdFrame;

/**
 * Cursor position/visibility snapshot (`vgd_cursor_state`).
 */
typedef struct VgdCursorState {
  /**
   * Desktop coordinates of the shape's top-left pixel (can be
   * negative when the hotspot hangs off the display edge).
   */
  int32_t x;
  int32_t y;
  /**
   * 0 hidden, 1 visible.
   */
  uint32_t visible;
  /**
   * Even counter bumped after each complete shape rewrite (0 = no
   * shape yet). Re-fetch the shape when it changes.
   */
  uint32_t shape_generation;
  uint64_t position_qpc;
} VgdCursorState;

/**
 * Cursor shape metadata; pixels land in the caller's buffer at a
 * `width * 4` pitch (32bpp, `VGD_CURSOR_KIND_*`).
 */
typedef struct VgdCursorShape {
  uint32_t kind;
  uint32_t width;
  uint32_t height;
  uint32_t hotspot_x;
  uint32_t hotspot_y;
  /**
   * The generation this copy is valid for.
   */
  uint32_t generation;
} VgdCursorShape;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Win32 error code of the most recent failing FFI call on the calling
 * thread (0 = none recorded). Read it immediately after a NULL /
 * [`VGD_ERR_IO`] return; success does not clear it.
 */
uint32_t vgd_last_error(void);

/**
 * Open the LuminalVGD control device. NULL when the driver is absent —
 * the caller falls back to another backend.
 */
struct VgdDeviceHandle *vgd_device_open(void);

void vgd_device_close(struct VgdDeviceHandle *dev);

int32_t vgd_handshake(struct VgdDeviceHandle *dev, struct VgdCaps *out);

int32_t vgd_create_monitor(struct VgdDeviceHandle *dev,
                           const struct VgdCreateRequest *req,
                           struct VgdCreateReply *out);

/**
 * Grow a LIVE monitor's advertised mode list — no destroy/create cycle,
 * so no `DBT_DEVNODES_CHANGED` broadcast and no monitor churn (proto
 * 0.5, driver build 17+).
 *
 * The motivating case: a client is already streaming a display created
 * at its base refresh rate, and only then launches a frame-generation
 * title. Calling this with `{base, doubled}` makes the doubled rate
 * selectable on the existing display.
 *
 * # Contract the caller must honor
 *
 * - **Gate on `VgdCaps.caps & VGD_CAP_DYNAMIC_MODES`.** Against an older
 *   driver the opcode is unknown and this returns [`VGD_ERR_IO`]; that
 *   is safe (never a false success) but it is a wasted round trip, and
 *   the log line the caller writes should name the driver's version.
 * - **Additive only.** The driver unions the request into the current
 *   list and NEVER removes a mode; `modes[0]` of the created monitor
 *   stays preferred. Passing a shorter list does not shrink anything.
 * - **Degrade, never refuse.** Treat both `VGD_ERR_IO` and any negative
 *   `result` as "the mode list is unchanged, carry on with the session".
 *   A failed update is never a reason to tear a stream down.
 * - **`result == 0` means ACCEPTED, not applied.** The driver completes
 *   the request before it calls the OS. The applied/failed outcome shows
 *   up in ETW and as the monitor's sticky `last_error` in the status
 *   reply. `result == 0` with neither flag set is the only shape that
 *   means "every mode you asked for is advertised right now"; with
 *   `VGD_UPDATE_PENDING` set, an update is still outstanding, and if it
 *   does not land the previous list stays in force and this exact
 *   request can simply be sent again.
 * - **Check `accepted` against `requested`.** They differ when the
 *   monitor's list is already at its cap; the modes that fit were still
 *   applied.
 */
int32_t vgd_update_modes(struct VgdDeviceHandle *dev,
                         const struct VgdUpdateModesRequest *req,
                         struct VgdUpdateModesReply *out);

int32_t vgd_destroy_monitor(struct VgdDeviceHandle *dev, uint64_t session_id);

/**
 * Feed the per-lease watchdog; call at least once per `watchdog_secs`.
 */
int32_t vgd_ping(struct VgdDeviceHandle *dev, uint64_t session_id);

/**
 * Map the frame ring for a created monitor. NULL until the driver has
 * created the section (retry briefly after create).
 */
struct VgdRingHandle *vgd_ring_open(uint64_t session_id, uint32_t ring_slots);

void vgd_ring_close(struct VgdRingHandle *ring);

int32_t vgd_ring_status(struct VgdRingHandle *ring, struct VgdRingStatus *out);

/**
 * Claim the freshest published frame. Returns `true` and fills `out`
 * when a frame was checked out; `false` when nothing is published.
 */
bool vgd_ring_claim(struct VgdRingHandle *ring, struct VgdFrame *out);

/**
 * Release a claimed frame back to the driver. Exactly once per claim.
 */
void vgd_ring_release(struct VgdRingHandle *ring, uint32_t index);

/**
 * Map the shared cursor section for a created monitor (requires
 * `VGD_CAP_HW_CURSOR`). NULL when the driver has no cursor plane for
 * this monitor — the cursor is then composed into frames as before.
 */
struct VgdCursorHandle *vgd_cursor_open(uint64_t session_id);

void vgd_cursor_close(struct VgdCursorHandle *cursor);

/**
 * Position/visibility snapshot (cheap; poll every frame).
 */
int32_t vgd_cursor_state(struct VgdCursorHandle *cursor, struct VgdCursorState *out);

/**
 * Copy the current shape into `buf` (`buf_len` ≥ width*height*4; size
 * `VGD_CURSOR_SHAPE_BUFFER_SIZE` always suffices). Returns `true` and
 * fills `out` on a consistent copy; `false` when no shape is published
 * yet or the driver was mid-rewrite (retry next frame).
 */
bool vgd_cursor_shape(struct VgdCursorHandle *cursor,
                      uint8_t *buf,
                      uint32_t buf_len,
                      struct VgdCursorShape *out);

/**
 * Compose the named shared-texture name for (session, generation, slot)
 * into `out` (capacity 96 u16s, NUL-padded). Returns the char count.
 * Open with `ID3D11Device1::OpenSharedResourceByName`.
 */
uint32_t vgd_slot_texture_name(uint64_t session_id,
                               uint32_t generation,
                               uint32_t slot,
                               uint16_t *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LUMINAL_VGD_H */
