/* SPDX-License-Identifier: AGPL-3.0-only
 * Generated by luminal-vgd-ffi's build.rs (cbindgen) — do not edit.
 *
 * Link (MSYS2 UCRT64):
 *   cargo build -p luminal-vgd-ffi --release --target x86_64-pc-windows-gnullvm
 *   ... -lluminal_vgd_ffi -lcfgmgr32 -lws2_32 -luserenv -lntdll -lbcrypt
 */

#ifndef LUMINAL_VGD_H
#define LUMINAL_VGD_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * OS-level failure (I/O error, device unreachable) as opposed to a
 * negative proto `err::*` code from the driver.
 */
#define VGD_ERR_IO -1000

/**
 * Capability bits of `VgdCaps.caps` the backend gates on (literal
 * mirrors of proto `caps::*`; the asserts below keep them honest —
 * cbindgen cannot evaluate cross-crate constants).
 */
#define VGD_CAP_HDR10 1

#define VGD_CAP_SDR10_BIT 4

#define VGD_CAP_HW_CURSOR 32

/**
 * `VgdCursorShape.kind` values (mirror proto `cursor_kind::*`).
 */
#define VGD_CURSOR_KIND_ALPHA 1

#define VGD_CURSOR_KIND_MASKED 3

/**
 * Worst-case shape buffer size for `vgd_cursor_shape` (256² 32bpp).
 */
#define VGD_CURSOR_SHAPE_BUFFER_SIZE ((256 * 256) * 4)

typedef struct VgdCursorHandle VgdCursorHandle;

typedef struct VgdDeviceHandle VgdDeviceHandle;

typedef struct VgdRingHandle VgdRingHandle;

/**
 * Handshake results the backend needs for capability gating.
 */
typedef struct VgdCaps {
  uint16_t proto_major;
  uint16_t proto_minor;
  uint32_t driver_build;
  uint32_t caps;
  uint32_t max_monitors;
  uint32_t watchdog_secs;
} VgdCaps;

/**
 * One display mode; `modes[0]` is preferred. Mirrors proto `ModeSpec`.
 */
typedef struct VgdModeSpec {
  uint32_t width;
  uint32_t height;
  uint32_t refresh_millihz;
} VgdModeSpec;

/**
 * Monitor creation parameters (see proto `CreateMonitorRequest` for full
 * field semantics; zero means "driver default" where the proto says so).
 */
typedef struct VgdCreateRequest {
  uint64_t session_id;
  uint64_t display_id;
  uint64_t adapter_luid;
  uint32_t lease_timeout_ms;
  uint32_t bit_depth;
  uint32_t hdr;
  uint32_t flags;
  uint32_t mode_count;
  struct VgdModeSpec modes[4];
  uint32_t physical_width_mm;
  uint32_t physical_height_mm;
  /**
   * NUL-padded UTF-16LE.
   */
  uint16_t friendly_name[32];
} VgdCreateRequest;

typedef struct VgdCreateReply {
  uint64_t session_id;
  uint64_t display_id;
  /**
   * `0` or a negative proto `err::*` code.
   */
  int32_t result;
  uint32_t ring_slots;
  uint32_t connector_index;
} VgdCreateReply;

/**
 * Snapshot of the ring header for health/fallback decisions.
 */
typedef struct VgdRingStatus {
  uint32_t generation;
  /**
   * proto `ring_state::*` (1 ACTIVE, 2 REBUILDING, 3 DEAD, 0 uninit).
   */
  uint32_t state;
  uint64_t latest_sequence;
  uint64_t frames_published;
  uint64_t frames_dropped;
  uint64_t heartbeat_qpc;
  uint64_t qpc_frequency;
} VgdRingStatus;

/**
 * A claimed (checked-out) frame. The driver will not overwrite this slot
 * until `vgd_ring_release`.
 */
typedef struct VgdFrame {
  uint32_t index;
  /**
   * Bake into the texture name; re-claim if the header generation has
   * moved on by the time the texture is opened.
   */
  uint32_t generation;
  uint64_t sequence;
  uint64_t present_qpc;
} VgdFrame;

/**
 * Cursor position/visibility snapshot (`vgd_cursor_state`).
 */
typedef struct VgdCursorState {
  /**
   * Desktop coordinates of the shape's top-left pixel (can be
   * negative when the hotspot hangs off the display edge).
   */
  int32_t x;
  int32_t y;
  /**
   * 0 hidden, 1 visible.
   */
  uint32_t visible;
  /**
   * Even counter bumped after each complete shape rewrite (0 = no
   * shape yet). Re-fetch the shape when it changes.
   */
  uint32_t shape_generation;
  uint64_t position_qpc;
} VgdCursorState;

/**
 * Cursor shape metadata; pixels land in the caller's buffer at a
 * `width * 4` pitch (32bpp, `VGD_CURSOR_KIND_*`).
 */
typedef struct VgdCursorShape {
  uint32_t kind;
  uint32_t width;
  uint32_t height;
  uint32_t hotspot_x;
  uint32_t hotspot_y;
  /**
   * The generation this copy is valid for.
   */
  uint32_t generation;
} VgdCursorShape;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Open the LuminalVGD control device. NULL when the driver is absent —
 * the caller falls back to another backend.
 */
struct VgdDeviceHandle *vgd_device_open(void);

void vgd_device_close(struct VgdDeviceHandle *dev);

int32_t vgd_handshake(struct VgdDeviceHandle *dev, struct VgdCaps *out);

int32_t vgd_create_monitor(struct VgdDeviceHandle *dev,
                           const struct VgdCreateRequest *req,
                           struct VgdCreateReply *out);

int32_t vgd_destroy_monitor(struct VgdDeviceHandle *dev, uint64_t session_id);

/**
 * Feed the per-lease watchdog; call at least once per `watchdog_secs`.
 */
int32_t vgd_ping(struct VgdDeviceHandle *dev, uint64_t session_id);

/**
 * Map the frame ring for a created monitor. NULL until the driver has
 * created the section (retry briefly after create).
 */
struct VgdRingHandle *vgd_ring_open(uint64_t session_id, uint32_t ring_slots);

void vgd_ring_close(struct VgdRingHandle *ring);

int32_t vgd_ring_status(struct VgdRingHandle *ring, struct VgdRingStatus *out);

/**
 * Claim the freshest published frame. Returns `true` and fills `out`
 * when a frame was checked out; `false` when nothing is published.
 */
bool vgd_ring_claim(struct VgdRingHandle *ring, struct VgdFrame *out);

/**
 * Release a claimed frame back to the driver. Exactly once per claim.
 */
void vgd_ring_release(struct VgdRingHandle *ring, uint32_t index);

/**
 * Map the shared cursor section for a created monitor (requires
 * `VGD_CAP_HW_CURSOR`). NULL when the driver has no cursor plane for
 * this monitor — the cursor is then composed into frames as before.
 */
struct VgdCursorHandle *vgd_cursor_open(uint64_t session_id);

void vgd_cursor_close(struct VgdCursorHandle *cursor);

/**
 * Position/visibility snapshot (cheap; poll every frame).
 */
int32_t vgd_cursor_state(struct VgdCursorHandle *cursor, struct VgdCursorState *out);

/**
 * Copy the current shape into `buf` (`buf_len` ≥ width*height*4; size
 * `VGD_CURSOR_SHAPE_BUFFER_SIZE` always suffices). Returns `true` and
 * fills `out` on a consistent copy; `false` when no shape is published
 * yet or the driver was mid-rewrite (retry next frame).
 */
bool vgd_cursor_shape(struct VgdCursorHandle *cursor,
                      uint8_t *buf,
                      uint32_t buf_len,
                      struct VgdCursorShape *out);

/**
 * Compose the named shared-texture name for (session, generation, slot)
 * into `out` (capacity 96 u16s, NUL-padded). Returns the char count.
 * Open with `ID3D11Device1::OpenSharedResourceByName`.
 */
uint32_t vgd_slot_texture_name(uint64_t session_id,
                               uint32_t generation,
                               uint32_t slot,
                               uint16_t *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LUMINAL_VGD_H */
