// SPDX-License-Identifier: AGPL-3.0-only
//! Control plane: EvtIddCxDeviceIoControl → [`crate::dispatch::dispatch`],
//! effect application, per-handle contexts, and registry persistence.

use core::ptr::null_mut;
use core::sync::atomic::{AtomicU32, Ordering};

use wdk_sys::{
    call_unsafe_wdf_function_binding, NTSTATUS, PVOID, STATUS_DEVICE_NOT_READY,
    STATUS_INVALID_DEVICE_REQUEST, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, ULONG,
    UNICODE_STRING, WDFDEVICE, WDFFILEOBJECT, WDFKEY, WDFREQUEST,
};
use windows::Win32::Foundation::{CloseHandle, GetLastError, HANDLE};
use windows::Win32::Security::{
    CheckTokenMembership, CreateWellKnownSid, EqualSid, GetTokenInformation, TokenGroups,
    TokenUser, WinBuiltinAdministratorsSid, WinLocalSystemSid, PSID, SECURITY_MAX_SID_SIZE,
    TOKEN_GROUPS, TOKEN_QUERY, TOKEN_USER, WELL_KNOWN_SID_TYPE,
};
use windows::Win32::System::Threading::{GetCurrentThread, OpenThreadToken};

/// `SE_GROUP_ENABLED` (winnt.h) — not generated by the `windows` crate's
/// `Win32_Security` feature set.
const SE_GROUP_ENABLED: u32 = 0x0000_0004;

use std::sync::mpsc;

use super::PROVIDER;
use super::{dxgi, monitors, OsHandle, Shell};
use crate::dispatch::{
    dispatch, Effect, HandleCtx, Status, TDR_DUCK_DEVICE, TDR_DUCK_DISPLAY,
};
use luminal_driver_proto::ioctl;

const STATUS_ACCESS_DENIED: NTSTATUS = 0xC000_0022u32 as NTSTATUS;

/// Reference string of the control device interface. Opens through the
/// enumerated interface symlink carry `\LuminalVGDControl` as the file
/// name; that name (and only that name) is subject to the DESIGN.md §6
/// SYSTEM+Administrators check below.
static CONTROL_REF: [u16; 18] = super::wide("LuminalVGDControl");

pub(crate) fn control_ref_unicode() -> UNICODE_STRING {
    let bytes = ((CONTROL_REF.len() - 1) * 2) as u16;
    UNICODE_STRING {
        Length: bytes,
        MaximumLength: bytes + 2,
        Buffer: CONTROL_REF.as_ptr().cast_mut(),
    }
}

/// Case-insensitive check whether `name` (a file-object name) addresses
/// the control interface: `\LuminalVGDControl` with or without the
/// leading backslash.
fn is_control_name(name: &[u16]) -> bool {
    let want = &CONTROL_REF[..CONTROL_REF.len() - 1]; // strip NUL
    let name = if name.first() == Some(&(b'\\' as u16)) { &name[1..] } else { name };
    name.len() == want.len()
        && name
            .iter()
            .zip(want.iter())
            .all(|(&a, &b)| char_fold(a) == char_fold(b))
}

fn char_fold(c: u16) -> u16 {
    match c {
        0x61..=0x7A => c - 0x20, // a-z → A-Z (the ref string is ASCII)
        _ => c,
    }
}

fn well_known_sid(kind: WELL_KNOWN_SID_TYPE, buf: &mut [u8; SECURITY_MAX_SID_SIZE as usize]) -> Option<PSID> {
    let mut len = buf.len() as u32;
    unsafe {
        CreateWellKnownSid(kind, None, Some(PSID(buf.as_mut_ptr().cast())), &mut len).ok()?;
    }
    Some(PSID(buf.as_mut_ptr().cast()))
}

// Stages of the §6 authorization check, traced verbatim on every failure
// so a single ETW capture localizes a denial without a re-sign round
// (lesson from build 8: the check had exactly one untraceable deny path,
// and the installed-service context tripped it with zero diagnostics).
const STAGE_POLICY: u32 = 0; // check ran to completion; caller not SYSTEM/admin
const STAGE_IMPERSONATE: u32 = 1; // WdfRequestImpersonate failed (code = NTSTATUS)
const STAGE_OPEN_TOKEN: u32 = 2; // OpenThreadToken failed (code = Win32 error)
const STAGE_QUERY_USER: u32 = 3; // GetTokenInformation(TokenUser) failed
const STAGE_QUERY_GROUPS: u32 = 4; // GetTokenInformation(TokenGroups) failed
const STAGE_SID: u32 = 5; // CreateWellKnownSid failed
const STAGE_CHECK_MEMBERSHIP: u32 = 6; // CheckTokenMembership fallback failed

const OUTCOME_UNSET: u32 = 0;
const OUTCOME_SYSTEM: u32 = 1;
const OUTCOME_ADMIN: u32 = 2;
const OUTCOME_REFUSED: u32 = 3;

/// Result of evaluating the DESIGN.md §6 policy against a request's caller.
#[derive(Clone, Copy, Debug)]
pub(crate) enum AuthOutcome {
    /// Caller's token inspected: SYSTEM (`how` 1) or an elevated
    /// Administrator (`how` 2).
    Authorized { how: u32 },
    /// Caller's token inspected; it is neither. Fail closed.
    Refused,
    /// The token could not be evaluated at all (stage/code say where).
    /// The policy question is unanswered — never treat as authorized.
    Unavailable { stage: u32, code: u32 },
}

/// Filled by [`evt_impersonate`] while the caller's token is on the thread.
struct AuthProbe {
    outcome: AtomicU32,
    stage: AtomicU32,
    code: AtomicU32,
}

impl AuthProbe {
    const fn new() -> Self {
        Self {
            outcome: AtomicU32::new(OUTCOME_UNSET),
            stage: AtomicU32::new(0),
            code: AtomicU32::new(0),
        }
    }

    /// Record the FIRST failing stage only — later fallback attempts must
    /// not overwrite the diagnosis of where the primary path broke.
    fn fail(&self, stage: u32, code: u32) {
        if self
            .stage
            .compare_exchange(0, stage, Ordering::AcqRel, Ordering::Acquire)
            .is_ok()
        {
            self.code.store(code, Ordering::Release);
        }
    }
}

/// Direct token inspection: the token's *user* SID must be LocalSystem, or
/// its group list must carry BUILTIN\Administrators with `SE_GROUP_ENABLED`.
/// A filtered (non-elevated) admin token carries that SID deny-only —
/// without the enabled attribute — so it is correctly refused. Deliberately
/// no `CheckTokenMembership`/`AccessCheck`: build 8 used it and production
/// service callers were refused with no way to tell why; plain
/// `GetTokenInformation` + `EqualSid` has no hidden evaluation semantics.
unsafe fn inspect_token(token: HANDLE, probe: &AuthProbe) {
    // 8-aligned buffers: TOKEN_USER embeds pointers.
    let mut user_buf = [0u64; (SECURITY_MAX_SID_SIZE as usize + 32).div_ceil(8)];
    let mut ret_len = 0u32;
    if GetTokenInformation(
        token,
        TokenUser,
        Some(user_buf.as_mut_ptr().cast()),
        (user_buf.len() * 8) as u32,
        &mut ret_len,
    )
    .is_err()
    {
        probe.fail(STAGE_QUERY_USER, GetLastError().0);
        return;
    }
    let user_sid = (*(user_buf.as_ptr() as *const TOKEN_USER)).User.Sid;

    let mut sid_buf = [0u8; SECURITY_MAX_SID_SIZE as usize];
    let Some(system) = well_known_sid(WinLocalSystemSid, &mut sid_buf) else {
        probe.fail(STAGE_SID, GetLastError().0);
        return;
    };
    if EqualSid(user_sid, system).is_ok() {
        probe.outcome.store(OUTCOME_SYSTEM, Ordering::Release);
        return;
    }

    let mut need = 0u32;
    let _ = GetTokenInformation(token, TokenGroups, None, 0, &mut need);
    if need == 0 {
        probe.fail(STAGE_QUERY_GROUPS, GetLastError().0);
        return;
    }
    let mut groups_buf = vec![0u64; (need as usize).div_ceil(8)];
    if GetTokenInformation(
        token,
        TokenGroups,
        Some(groups_buf.as_mut_ptr().cast()),
        (groups_buf.len() * 8) as u32,
        &mut ret_len,
    )
    .is_err()
    {
        probe.fail(STAGE_QUERY_GROUPS, GetLastError().0);
        return;
    }
    let Some(admins) = well_known_sid(WinBuiltinAdministratorsSid, &mut sid_buf) else {
        probe.fail(STAGE_SID, GetLastError().0);
        return;
    };
    let groups = &*(groups_buf.as_ptr() as *const TOKEN_GROUPS);
    let entries =
        core::slice::from_raw_parts(groups.Groups.as_ptr(), groups.GroupCount as usize);
    for group in entries {
        if (group.Attributes & SE_GROUP_ENABLED) != 0 && EqualSid(group.Sid, admins).is_ok() {
            probe.outcome.store(OUTCOME_ADMIN, Ordering::Release);
            return;
        }
    }
    probe.outcome.store(OUTCOME_REFUSED, Ordering::Release);
}

/// Runs inside `WdfRequestImpersonate` with the caller's token on the
/// thread. Ladder, because no single token-access path works in every
/// deployment (build 9 lesson — WUDFHost's account gates what it can open):
///
/// 1. `OpenThreadToken(OpenAsSelf=FALSE)` — access-checked as the client;
///    works at SecurityImpersonation (SYSTEM can always open SYSTEM's
///    token) but not at Identification (such tokens can't be used for
///    access checks).
/// 2. `OpenThreadToken(OpenAsSelf=TRUE)` — access-checked as the WUDFHost
///    account; works when the client token's DACL grants it.
/// 3. `CheckTokenMembership(NULL, …)` — the documented service-side
///    pattern for evaluating an impersonated client without managing a
///    token handle.
///
/// Every failed rung records its stage+code (first failure wins) so a
/// trace shows exactly which paths this machine refuses.
unsafe extern "C" fn evt_impersonate(_request: WDFREQUEST, context: PVOID) {
    let probe = &*(context as *const AuthProbe);
    let mut token = HANDLE::default();
    let mut opened =
        OpenThreadToken(GetCurrentThread(), TOKEN_QUERY, false, &mut token).is_ok();
    if !opened {
        probe.fail(STAGE_OPEN_TOKEN, GetLastError().0);
        opened = OpenThreadToken(GetCurrentThread(), TOKEN_QUERY, true, &mut token).is_ok();
    }
    if opened {
        inspect_token(token, probe);
        let _ = CloseHandle(token);
        if probe.outcome.load(Ordering::Acquire) != OUTCOME_UNSET {
            return;
        }
    }

    // Rung 3: direct membership checks on the thread token. Only a run in
    // which every rung answered (no errors) may conclude "refused".
    let mut sid_buf = [0u8; SECURITY_MAX_SID_SIZE as usize];
    let mut definitive = true;
    for (kind, outcome) in
        [(WinLocalSystemSid, OUTCOME_SYSTEM), (WinBuiltinAdministratorsSid, OUTCOME_ADMIN)]
    {
        let Some(sid) = well_known_sid(kind, &mut sid_buf) else {
            probe.fail(STAGE_SID, GetLastError().0);
            definitive = false;
            continue;
        };
        let mut member = windows::Win32::Foundation::FALSE;
        match CheckTokenMembership(None, sid, &mut member) {
            Ok(()) if member.as_bool() => {
                probe.outcome.store(outcome, Ordering::Release);
                return;
            }
            Ok(()) => {}
            Err(_) => {
                probe.fail(STAGE_CHECK_MEMBERSHIP, GetLastError().0);
                definitive = false;
            }
        }
    }
    if definitive {
        probe.outcome.store(OUTCOME_REFUSED, Ordering::Release);
    }
}

/// Evaluate the §6 policy against the caller of `request` (any request
/// type — creates and IOCTLs both carry the client identity in UMDF).
/// Prefers SecurityImpersonation (lets rung 1 work); falls back to
/// SecurityIdentification for clients that granted less at open.
pub(crate) unsafe fn authorize_request(request: WDFREQUEST) -> AuthOutcome {
    let probe = AuthProbe::new();
    let mut status = call_unsafe_wdf_function_binding!(
        WdfRequestImpersonate,
        request,
        wdk_sys::_SECURITY_IMPERSONATION_LEVEL::SecurityImpersonation,
        Some(evt_impersonate),
        (&probe as *const AuthProbe) as PVOID
    );
    if status != STATUS_SUCCESS {
        probe.fail(STAGE_IMPERSONATE, status as u32);
        status = call_unsafe_wdf_function_binding!(
            WdfRequestImpersonate,
            request,
            wdk_sys::_SECURITY_IMPERSONATION_LEVEL::SecurityIdentification,
            Some(evt_impersonate),
            (&probe as *const AuthProbe) as PVOID
        );
    }
    if status != STATUS_SUCCESS {
        return AuthOutcome::Unavailable {
            stage: STAGE_IMPERSONATE,
            code: probe.code.load(Ordering::Acquire),
        };
    }
    match probe.outcome.load(Ordering::Acquire) {
        how @ (OUTCOME_SYSTEM | OUTCOME_ADMIN) => AuthOutcome::Authorized { how },
        OUTCOME_REFUSED => AuthOutcome::Refused,
        _ => AuthOutcome::Unavailable {
            stage: probe.stage.load(Ordering::Acquire),
            code: probe.code.load(Ordering::Acquire),
        },
    }
}

/// Registry value under the device hardware key holding the persisted
/// state blob (identity reservations + permanent pool).
static VALUE_NAME: [u16; 16] = super::wide("LuminalVgdState");

fn value_name_unicode() -> UNICODE_STRING {
    let bytes = ((VALUE_NAME.len() - 1) * 2) as u16;
    UNICODE_STRING {
        Length: bytes,
        MaximumLength: bytes + 2,
        Buffer: VALUE_NAME.as_ptr().cast_mut(),
    }
}

const PLUGPLAY_REGKEY_DEVICE: ULONG = 1;
const KEY_READ_ACCESS: u32 = 0x2001_9; // KEY_READ
const KEY_WRITE_ACCESS: u32 = 0x2000_6; // KEY_WRITE
const REG_BINARY_TYPE: ULONG = 3;

unsafe fn open_device_key(device: WDFDEVICE, access: u32) -> Option<WDFKEY> {
    let mut key: WDFKEY = null_mut();
    let status = call_unsafe_wdf_function_binding!(
        WdfDeviceOpenRegistryKey,
        device,
        PLUGPLAY_REGKEY_DEVICE,
        access,
        wdk_sys::WDF_NO_OBJECT_ATTRIBUTES,
        &mut key
    );
    (status == STATUS_SUCCESS).then_some(key)
}

/// Read the persisted blob at device add (before the shell global
/// exists). Any failure is "no state" — parsing is defensive anyway.
pub unsafe fn read_persisted(device: WDFDEVICE) -> Option<Vec<u8>> {
    let key = open_device_key(device, KEY_READ_ACCESS)?;
    let name = value_name_unicode();
    let mut buf = vec![0u8; 4096];
    let mut got: ULONG = 0;
    let mut vtype: ULONG = 0;
    let status = call_unsafe_wdf_function_binding!(
        WdfRegistryQueryValue,
        key,
        &name,
        buf.len() as ULONG,
        buf.as_mut_ptr().cast::<core::ffi::c_void>(),
        &mut got,
        &mut vtype
    );
    call_unsafe_wdf_function_binding!(WdfRegistryClose, key);
    if status != STATUS_SUCCESS || vtype != REG_BINARY_TYPE || got == 0 {
        return None;
    }
    buf.truncate(got as usize);
    Some(buf)
}

/// Registry value selecting the TDR response policy (build 16 gate), a
/// REG_DWORD under the SAME devnode `Device Parameters` key as the state
/// blob: `HKLM\SYSTEM\CurrentControlSet\Enum\ROOT\DISPLAY\000x\Device
/// Parameters\LuminalVgdTdrDuckMode`. That key survives driver-package
/// updates (it is how identity retention works across reinstalls), so an
/// operator can restore the legacy behaviour with regedit + `pnputil
/// /restart-device` and no reinstall.
const TDR_MODE_VALUE_INIT: [u16; 22] = super::wide("LuminalVgdTdrDuckMode");
/// `wide()` TRUNCATES silently when the array is a byte short, which would
/// send an unterminated (and wrong-length) name to WdfRegistryQueryULong —
/// the gate would then read as "absent" on every machine and the override
/// would be undiscoverably dead. Catch it at compile time instead of in a
/// signing round: the last element must be the NUL terminator.
const _: () = assert!(
    TDR_MODE_VALUE_INIT[TDR_MODE_VALUE_INIT.len() - 1] == 0,
    "TDR_MODE_VALUE array is too short for its string (no NUL terminator)"
);
static TDR_MODE_VALUE: [u16; 22] = TDR_MODE_VALUE_INIT;

fn tdr_mode_name_unicode() -> UNICODE_STRING {
    let bytes = ((TDR_MODE_VALUE.len() - 1) * 2) as u16;
    UNICODE_STRING {
        Length: bytes,
        MaximumLength: bytes + 2,
        Buffer: TDR_MODE_VALUE.as_ptr().cast_mut(),
    }
}

/// Not in wdk-sys' generated status constants; the value is fixed by the
/// NT status contract. This is the ORDINARY outcome — the value is absent
/// on every machine that never configured the gate.
const STATUS_OBJECT_NAME_NOT_FOUND: NTSTATUS = 0xC000_0034u32 as NTSTATUS;

/// Gate-read stages, so a trace says WHERE a read failed, not just that it
/// did (constraint 4 — the 2026-07 blind-signing lesson).
const TDR_GATE_STAGE_OPEN: u32 = 0;
const TDR_GATE_STAGE_QUERY: u32 = 1;
const TDR_GATE_STAGE_RANGE: u32 = 2;

/// Gate provenance, reported in the `TdrDuckConfig` event.
const TDR_GATE_SOURCE_DEFAULT: u32 = 0;
const TDR_GATE_SOURCE_REGISTRY: u32 = 1;

/// Read the TDR duck-mode gate at device add (before the shell global
/// exists — must not call `Shell::get`). Returns `(mode, source)`.
///
/// Every failure defaults to [`TDR_DUCK_DEVICE`] so the shipped behaviour
/// is the spec-conformant one (DESIGN.md §3.3 rule 2) even on a machine
/// whose registry cannot be read — but "absent" and "unreadable" are
/// traced differently, because a box where `WdfDeviceOpenRegistryKey`
/// fails must not look identical to a box that was simply never
/// configured. Deliberately NOT seeded by the INF's AddReg: HKR there
/// rewrites on every package update and would silently stamp an
/// operator's override back to the default mid-upgrade.
pub unsafe fn read_tdr_duck_mode(device: WDFDEVICE) -> (u32, u32) {
    let Some(key) = open_device_key(device, KEY_READ_ACCESS) else {
        tracelogging::write_event!(
            PROVIDER,
            "TdrDuckConfigReadFailed",
            level(Warning),
            u32("stage", &TDR_GATE_STAGE_OPEN),
            i32("code", &0i32)
        );
        return (TDR_DUCK_DEVICE, TDR_GATE_SOURCE_DEFAULT);
    };
    let name = tdr_mode_name_unicode();
    let mut value: ULONG = 0;
    let status =
        call_unsafe_wdf_function_binding!(WdfRegistryQueryULong, key, &name, &mut value);
    call_unsafe_wdf_function_binding!(WdfRegistryClose, key);
    if status != STATUS_SUCCESS {
        if status != STATUS_OBJECT_NAME_NOT_FOUND {
            tracelogging::write_event!(
                PROVIDER,
                "TdrDuckConfigReadFailed",
                level(Warning),
                u32("stage", &TDR_GATE_STAGE_QUERY),
                i32("code", &status)
            );
        }
        return (TDR_DUCK_DEVICE, TDR_GATE_SOURCE_DEFAULT);
    }
    if value != TDR_DUCK_DEVICE && value != TDR_DUCK_DISPLAY {
        tracelogging::write_event!(
            PROVIDER,
            "TdrDuckConfigReadFailed",
            level(Warning),
            u32("stage", &TDR_GATE_STAGE_RANGE),
            i32("code", &(value as i32))
        );
        return (TDR_DUCK_DEVICE, TDR_GATE_SOURCE_DEFAULT);
    }
    (value, TDR_GATE_SOURCE_REGISTRY)
}

/// Announce the policy this binary is actually running under. THE most
/// important new event of build 16: it makes "which TDR behaviour is this
/// signed driver using" answerable from a single trace, instead of a
/// signing round spent guessing.
pub fn trace_tdr_duck_config(mode: u32, source: u32) {
    tracelogging::write_event!(
        PROVIDER,
        "TdrDuckConfig",
        level(Informational),
        u32("mode", &mode),
        u32("source", &source),
        u32("build", &super::DRIVER_BUILD)
    );
}

unsafe fn write_persisted(blob: &[u8]) {
    let shell = Shell::get();
    let Some(device) = shell.wdf_device() else {
        // Device already tore down (clear_wdf_device at D3Final): the
        // write is dropped, not applied to a destroyed handle. Traced —
        // the next start re-reads the previous blob.
        tracelogging::write_event!(PROVIDER, "PersistSkippedNoDevice", level(Warning));
        return;
    };
    let Some(key) = open_device_key(device.0.cast(), KEY_WRITE_ACCESS) else {
        return;
    };
    let name = value_name_unicode();
    let status = call_unsafe_wdf_function_binding!(
        WdfRegistryAssignValue,
        key,
        &name,
        REG_BINARY_TYPE,
        blob.len() as ULONG,
        blob.as_ptr().cast::<core::ffi::c_void>().cast_mut()
    );
    call_unsafe_wdf_function_binding!(WdfRegistryClose, key);
    if status != STATUS_SUCCESS {
        tracelogging::write_event!(
            PROVIDER,
            "PersistFailed",
            level(Error),
            i32("status", &status)
        );
    }
}

/// Work items for the effects worker thread. Everything here calls into
/// IddCx and/or D3D, which must never happen on an IddCx callback or WDF
/// timer frame — those are win32k callouts, and calling back in deadlocks
/// against the locks win32k holds while calling us (0x1b8 storms,
/// builds 6/7; see CLAUDE.md).
pub(crate) enum EffectsTask {
    Apply(Vec<Effect>),
    /// Deferred EvtIddCxAdapterInitFinished bring-up: the DXGI walk,
    /// DeviceState::startup (permanent-pool replug), then publishing the
    /// adapter handle — which flips Shell::ready and un-gates session
    /// IOCTLs, in exactly that order. `epoch` was captured at queue time;
    /// a D3Final teardown in between bumps it, and the stale task must
    /// then do nothing (the adapter object it carries is destroyed).
    AdapterReady { adapter: OsHandle, epoch: u64 },
    /// TDR duck-out: a frame worker observed device removal on its D3D
    /// device (a GPU reset). Depart every monitor so a failing OS TDR
    /// recovery can never wait on the indirect display path — the
    /// working hypothesis for the 5/17, 7/26 and 7/27 machine-wide
    /// wedges, where an IddCx display was the exclusive active display
    /// each time (docs/POSTMORTEM-2026-07-27.md). Parked monitors
    /// re-arrive via TdrReplug once the recovery poller sees the GPU
    /// answer device creation again.
    TdrDuck { epoch: u64 },
    /// Re-arrive the monitors parked by TdrDuck (queued by the recovery
    /// poller thread when the display stack answers again).
    TdrReplug { epoch: u64 },
    /// TDR DEVICE-duck (build 16 default, `TDR_DUCK_DEVICE`): a frame
    /// worker observed device removal, and by the time this runs it has
    /// ALREADY torn down the D3D device, abandoned the swapchain, retired
    /// the ring textures and marked the ring REBUILDING (swapchain.rs).
    /// This task deliberately does NOT depart anything — the IddCx monitor
    /// stays ARRIVED so Windows keeps a display path to compose onto. It
    /// only records the duck and starts the recovery poller, which keeps
    /// the ring heartbeat alive and waits for the OS's own
    /// unassign→assign to restore the transport.
    TdrDeviceDuck { epoch: u64, session_id: u64, reason_hr: i32 },
    /// The GPU answers again but the OS never re-assigned a swapchain:
    /// force ONE depart+re-arrive against a stack we just probed HEALTHY.
    /// This is the task spec's "depart only if OS recovery genuinely
    /// completes" clause — a clean modeset, not a last-display removal
    /// during a wedge.
    ///
    /// `sessions` is the LUID-scoped set the duck covered. It travels with
    /// the task for two reasons: the arm must not depart monitors on a
    /// healthy second adapter, and it must RE-CHECK the lock-free liveness
    /// mirror before departing anything — the queue-to-execution gap is
    /// enough for the OS to re-assign, and departing a display that is
    /// publishing again is exactly the failure build 16 exists to prevent.
    TdrRequalify { epoch: u64, sessions: Vec<u64> },
    /// The long recovery deadline expired with the GPU never answering
    /// (the machine-wide-wedge case): fall back to the legacy departure so
    /// a permanently dead stack cannot leave a phantom display arrived
    /// forever. The task spec's "or a long deadline expires" clause.
    /// Same scoping and same re-check as `TdrRequalify`.
    TdrDeadlineDepart { epoch: u64, sessions: Vec<u64> },
}

/// Spawn the effects worker at device add (from Shell::init). Returns
/// None on spawn failure; the queue functions then apply inline (the
/// pre-worker behavior) rather than dropping effects.
pub(crate) fn start_effects_thread() -> Option<mpsc::Sender<EffectsTask>> {
    let (tx, rx) = mpsc::channel::<EffectsTask>();
    let spawned = std::thread::Builder::new().name("vgd-effects".into()).spawn(move || {
        tracelogging::write_event!(PROVIDER, "EffectsWorkerSpawned", level(Informational));
        for task in rx {
            match task {
                EffectsTask::Apply(effects) => apply_now(effects),
                EffectsTask::AdapterReady { adapter, epoch } => {
                    run_adapter_ready(adapter, epoch)
                }
                EffectsTask::TdrDuck { epoch } => run_tdr_duck(epoch),
                EffectsTask::TdrReplug { epoch } => run_tdr_replug(epoch),
                EffectsTask::TdrDeviceDuck { epoch, session_id, reason_hr } => {
                    run_tdr_device_duck(epoch, session_id, reason_hr)
                }
                EffectsTask::TdrRequalify { epoch, sessions } => {
                    run_tdr_requalify(epoch, sessions)
                }
                EffectsTask::TdrDeadlineDepart { epoch, sessions } => {
                    run_tdr_deadline_depart(epoch, sessions)
                }
            }
        }
    });
    match spawned {
        Ok(_) => Some(tx),
        Err(_) => {
            tracelogging::write_event!(PROVIDER, "EffectsWorkerSpawnFailed", level(Error));
            None
        }
    }
}

/// Hand `task` to the effects worker. Returns the task back if the worker
/// is unavailable (never spawned, or its receiver is gone) so the caller
/// can fall back inline — a send error round-trips the same value.
fn send_task(task: EffectsTask) -> Option<EffectsTask> {
    let shell = Shell::get();
    let guard = shell.effects_tx.lock().unwrap();
    match guard.as_ref() {
        Some(tx) => match tx.send(task) {
            Ok(()) => None,
            Err(mpsc::SendError(task)) => Some(task),
        },
        None => Some(task),
    }
}

/// Queue dispatcher side effects for the effects worker (FIFO across all
/// producers). Callers may hold no locks the worker also takes; the send
/// itself never blocks. Inline fallback (traced) if the worker is gone —
/// effects must never be silently dropped.
pub(crate) fn queue_effects(effects: Vec<Effect>) {
    if effects.is_empty() {
        return;
    }
    if let Some(EffectsTask::Apply(effects)) = send_task(EffectsTask::Apply(effects)) {
        tracelogging::write_event!(PROVIDER, "EffectsInlineFallback", level(Warning));
        apply_now(effects);
    }
}

/// Queue the deferred adapter bring-up (EvtIddCxAdapterInitFinished).
pub(crate) fn queue_adapter_ready(adapter: OsHandle, epoch: u64) {
    if let Some(EffectsTask::AdapterReady { adapter, epoch }) =
        send_task(EffectsTask::AdapterReady { adapter, epoch })
    {
        tracelogging::write_event!(PROVIDER, "EffectsInlineFallback", level(Warning));
        run_adapter_ready(adapter, epoch);
    }
}

/// Called by a frame worker that observed device removal (a GPU reset).
/// One duck per incident: the pending CAS dedupes N workers failing off
/// one reset. The worker thread is not a callback frame, but the
/// departure work still belongs on the effects worker for ordering with
/// every other IddCx side effect; there is deliberately no inline
/// fallback here (a duck that cannot be queued is dropped and re-armed
/// by the next failing worker).
/// THE BUILD-16 GATE. Both frame-loop failure sites funnel through here,
/// so the two modes can never diverge between the acquire path and the
/// publish path.
///
/// `reason_hr` is the HRESULT that armed this duck — the device-removal
/// reason from `GetDeviceRemovedReason`, or the `create_device_on_luid`
/// failure at the re-arm site. It travels into the duck's own events so a
/// capture that has wrapped past `TdrDeviceRemoved` /
/// `SwapChainDeviceCreateFailed` can still say what a display stopped
/// publishing for; build 16 traced it only at the originating site. Zero
/// means "no HRESULT": the only such caller is the poller's own
/// close-the-latch-window re-arm, which is tagged `TdrDeviceDuckRearmed`.
pub(crate) fn queue_tdr_duck(session_id: u64, reason_hr: i32) {
    let shell = Shell::get();
    if shell
        .tdr_duck_pending
        .compare_exchange(false, true, std::sync::atomic::Ordering::SeqCst, std::sync::atomic::Ordering::SeqCst)
        .is_err()
    {
        return; // one already in flight
    }
    let epoch = shell.adapter_epoch();
    let task = if shell.tdr_duck_mode() == TDR_DUCK_DISPLAY {
        // Legacy build-14/15 behaviour, now opt-in. Traced distinctly so a
        // single field capture says which policy ran, without needing the
        // device-add event to still be in the buffer.
        tracelogging::write_event!(
            PROVIDER,
            "TdrLegacyDuck",
            level(Warning),
            u64("session", &session_id),
            i32("hresult", &reason_hr)
        );
        EffectsTask::TdrDuck { epoch }
    } else {
        EffectsTask::TdrDeviceDuck { epoch, session_id, reason_hr }
    };
    if send_task(task).is_some() {
        shell.tdr_duck_pending.store(false, std::sync::atomic::Ordering::SeqCst);
        tracelogging::write_event!(PROVIDER, "TdrDuckQueueFailed", level(Warning));
    }
}

/// How long the recovery poller keeps probing before giving up. A real
/// TDR recovers in ~2 minutes; a machine-wide wedge never does (only a
/// reboot clears it), and parked monitors must not linger forever.
const TDR_RECOVERY_BUDGET: std::time::Duration = std::time::Duration::from_secs(10 * 60);
const TDR_RECOVERY_PROBE_EVERY: std::time::Duration = std::time::Duration::from_secs(2);

/// Duck cycles per adapter epoch before giving up outright: a wedge
/// where device creation succeeds but activation still fails would
/// otherwise flap duck→replug→duck for as long as the wedge lasts.
const TDR_MAX_DUCK_CYCLES: u32 = 3;

/// One probe may hang this long before the poller counts it failed and
/// (rate-limited) tries a fresh one. A hung probe thread stays detached
/// and exits whenever the OS call finally returns.
const TDR_PROBE_DEADLINE: std::time::Duration = std::time::Duration::from_secs(15);
const TDR_PROBE_RESPAWN_AFTER_HANG: std::time::Duration = std::time::Duration::from_secs(60);

/// Drain the parked set and mark its rings dead — the shared give-up
/// path (deadline, spawn failure, cycle cap, stale replug/poller).
fn abandon_ducked(reason: &str) -> u64 {
    let shell = Shell::get();
    let parked: Vec<super::DuckedMonitor> = shell.ducked.lock().unwrap().drain(..).collect();
    for d in &parked {
        super::mark_ring_dead_arc(&d.ring);
    }
    let count = parked.len() as u64;
    if count > 0 {
        tracelogging::write_event!(
            PROVIDER,
            "TdrDuckAbandoned",
            level(Warning),
            str8("reason", reason),
            u64("abandoned", &count)
        );
    }
    count
}

/// A duck arriving long after the last successful recovery is a NEW
/// incident, not a continuation of the old flap — reset the budget so
/// sparse genuine TDRs across a long boot never exhaust it (which would
/// silently abandon permanent-pool monitors on the 4th). Shared by both
/// duck styles.
fn reset_cycles_if_new_incident() {
    let shell = Shell::get();
    const INCIDENT_WINDOW_MS: u64 = 10 * 60 * 1000;
    let last_recovery = shell.tdr_last_recovery_ms.load(std::sync::atomic::Ordering::SeqCst);
    if last_recovery != 0 && shell.now_ms().saturating_sub(last_recovery) > INCIDENT_WINDOW_MS {
        shell.tdr_duck_cycles.store(0, std::sync::atomic::Ordering::SeqCst);
    }
}

fn run_tdr_duck(epoch: u64) {
    let shell = Shell::get();
    if shell.adapter_epoch() != epoch {
        shell.tdr_duck_pending.store(false, std::sync::atomic::Ordering::SeqCst);
        tracelogging::write_event!(PROVIDER, "TdrDuckStale", level(Warning));
        return;
    }
    reset_cycles_if_new_incident();
    let parked = monitors::duck_all(epoch);
    if parked == 0 {
        // Nothing to park (already unplugged, or torn down mid-loop):
        // deliberately does NOT consume a cycle — spurious ducks must
        // not eat the incident budget.
        shell.tdr_duck_pending.store(false, std::sync::atomic::Ordering::SeqCst);
        return;
    }
    let cycle = shell.tdr_duck_cycles.fetch_add(1, std::sync::atomic::Ordering::SeqCst) + 1;
    tracelogging::write_event!(
        PROVIDER,
        "TdrDuckStart",
        level(Warning),
        u64("parked", &(parked as u64)),
        u32("cycle", &cycle)
    );
    if cycle > TDR_MAX_DUCK_CYCLES {
        // Flapping: recovery keeps "succeeding" and the monitors keep
        // failing. Stop churning modesets; only a reboot (or device
        // re-add, which resets the cycle counter) gets monitors back.
        abandon_ducked("cycle cap");
        shell.tdr_duck_pending.store(false, std::sync::atomic::Ordering::SeqCst);
        return;
    }
    // Probe the adapter the parked monitors actually render on.
    let probe_luid = shell
        .ducked
        .lock()
        .unwrap()
        .first()
        .map(|d| d.adapter_luid)
        .unwrap_or(0);

    // The poller lives on its own thread: the effects worker must stay
    // free for other effects while the GPU recovers (a parked recv()-loop
    // there would stall every later plug/unplug/persist).
    let spawned = std::thread::Builder::new().name("vgd-tdr-recovery".into()).spawn(move || {
        let shell = Shell::get();
        let deadline = std::time::Instant::now() + TDR_RECOVERY_BUDGET;
        // The D3D probe runs on a THROWAWAY thread: D3D11CreateDevice
        // against a wedged stack can block indefinitely, and the poller's
        // own clock (epoch/empty/deadline checks below) must keep ticking
        // regardless — a hung probe must not turn the bounded budget into
        // an unbounded one or leave tdr_duck_pending stuck forever.
        let mut probe: Option<(std::thread::JoinHandle<bool>, std::time::Instant)> = None;
        let mut last_hang_at: Option<std::time::Instant> = None;
        loop {
            std::thread::sleep(TDR_RECOVERY_PROBE_EVERY);
            if shell.adapter_epoch() != epoch {
                // Device teardown while parked. duck_all's own epoch
                // re-check covers a teardown racing the park loop, but
                // this poller may still own entries parked BEFORE the
                // teardown's drain — clean them deterministically.
                abandon_ducked("poller stale");
                shell.tdr_duck_pending.store(false, std::sync::atomic::Ordering::SeqCst);
                tracelogging::write_event!(PROVIDER, "TdrRecoveryPollerStale", level(Informational));
                return;
            }
            if shell.ducked.lock().unwrap().is_empty() {
                // Every parked session was destroyed or re-plugged.
                shell.tdr_duck_pending.store(false, std::sync::atomic::Ordering::SeqCst);
                return;
            }
            if let Some((handle, started)) = probe.take() {
                if handle.is_finished() {
                    let recovered = handle.join().unwrap_or(false);
                    if recovered {
                        tracelogging::write_event!(PROVIDER, "TdrRecoveryDetected", level(Informational));
                        if send_task(EffectsTask::TdrReplug { epoch }).is_some() {
                            // Effects worker gone (process teardown): park
                            // state is cleaned up by final exit.
                            shell.tdr_duck_pending.store(false, std::sync::atomic::Ordering::SeqCst);
                        }
                        return;
                    }
                } else if started.elapsed() >= TDR_PROBE_DEADLINE {
                    // Hung inside the OS call — detach and rate-limit
                    // respawns (each would hang the same way; the leak is
                    // bounded by the respawn interval and they exit when
                    // the call finally returns).
                    drop(handle);
                    last_hang_at = Some(std::time::Instant::now());
                    tracelogging::write_event!(PROVIDER, "TdrRecoveryProbeHung", level(Warning));
                } else {
                    probe = Some((handle, started));
                }
            }
            if probe.is_none() {
                let respawn_ok = match last_hang_at {
                    Some(at) => at.elapsed() >= TDR_PROBE_RESPAWN_AFTER_HANG,
                    None => true,
                };
                if respawn_ok {
                    if let Ok(handle) = std::thread::Builder::new()
                        .name("vgd-tdr-probe".into())
                        .spawn(move || super::swapchain::probe_adapter_on_luid(probe_luid))
                    {
                        probe = Some((handle, std::time::Instant::now()));
                    }
                }
            }
            if std::time::Instant::now() >= deadline {
                // Never recovered: the machine needs a reboot. Drop the
                // parked state deterministically (rings dead → the host
                // gives up cleanly; sessions die by DESTROY or lease).
                abandon_ducked("recovery deadline");
                shell.tdr_duck_pending.store(false, std::sync::atomic::Ordering::SeqCst);
                tracelogging::write_event!(PROVIDER, "TdrRecoveryGaveUp", level(Warning));
                return;
            }
        }
    });
    if spawned.is_err() {
        // No poller — treat as an immediate give-up so nothing leaks.
        abandon_ducked("poller spawn failed");
        shell.tdr_duck_pending.store(false, std::sync::atomic::Ordering::SeqCst);
        tracelogging::write_event!(PROVIDER, "TdrRecoveryPollerSpawnFailed", level(Error));
    }
}

fn run_tdr_replug(epoch: u64) {
    let shell = Shell::get();
    if shell.adapter_epoch() != epoch {
        abandon_ducked("replug stale");
        tracelogging::write_event!(PROVIDER, "TdrReplugStale", level(Warning));
    } else {
        monitors::replug_ducked();
        // Timestamp, not a counter reset: a flap re-ducks within seconds
        // (well inside the incident window) so the cap still binds; only
        // sustained stability starts a fresh budget.
        shell
            .tdr_last_recovery_ms
            .store(shell.now_ms().max(1), std::sync::atomic::Ordering::SeqCst);
    }
    shell.tdr_duck_pending.store(false, std::sync::atomic::Ordering::SeqCst);
}

// ---------------------------------------------------------------------
// Build 16: duck the DEVICE, not the DISPLAY (`TDR_DUCK_DEVICE`).
//
// Evidence (2026-07-30, verified): a corrected PCIe AER on the GPU root
// port produced DXGI_ERROR_DEVICE_REMOVED / DEVICE_RESET; 84 ms later the
// build-14 duck-out departed the ONLY active display, taking the active
// display count to zero BY DESIGN. 131 ms after that dwm.exe reported a
// black screen and Windows wrote a 0x1b8 live dump; QueryDisplayConfig
// then returned zero paths for 7.9 s and ERROR_NOT_SUPPORTED thereafter,
// never recovering. Windows logged NO Event 4101 — the OS never ran a
// TDR recovery cycle at all, so the thing the duck existed to get out of
// the way of never happened. The duck was not the root cause, but it
// converted a recoverable device removal into a machine-wide wedge.
//
// So: tear the DEVICE down (already done by the frame worker before it
// queues this) and keep the DISPLAY. DESIGN.md §3.3 rule 2 has specified
// exactly this from the start — "Monitors stay attached" — and the driver
// already relies on arrived-with-no-device being legal on every routine
// swapchain replacement (`evt_unassign` leaves the monitor arrived; the
// OS itself does this ~10 ms after every activation).
// ---------------------------------------------------------------------

/// Heartbeat cadence for a device-ducked ring. Must stay well under the
/// host's `RING_HEARTBEAT_STALE_MS` (2000): keeping the display alive is
/// pointless if the host concludes "driver gone" two seconds in. 250 ms
/// matches the frame worker's own `HEARTBEAT_EVERY`.
const TDR_DEVICE_TICK: std::time::Duration = std::time::Duration::from_millis(250);

/// Once the GPU answers device creation again, how long to let the OS
/// drive its own unassign→assign before forcing a requalify modeset. A
/// completed reset normally re-assigns within a few hundred ms, so this
/// is deliberately generous — the zero-modeset path should win whenever
/// it possibly can.
const TDR_REASSIGN_GRACE: std::time::Duration = std::time::Duration::from_secs(10);

/// Release the one-duck-in-flight latch. There is no device-duck state
/// object by design: `tdr_duck_pending` is the only thing that has to be
/// global, and the poller keeps everything else in its own locals.
fn finish_device_duck() {
    Shell::get()
        .tdr_duck_pending
        .store(false, std::sync::atomic::Ordering::SeqCst);
}

/// A poller exit arm could not reach the effects worker (process teardown,
/// or it never spawned). Constraint 4: an arm that silently does nothing is
/// indistinguishable in a trace from an arm that was never taken, and this
/// one decides whether the display is ever departed — the single most
/// consequential question in a build-16 capture.
///
/// There is deliberately NO inline fallback: an IddCx call from a poller
/// thread is exactly what §3.3 forbids. The monitor stays ARRIVED, which is
/// the safe residue in this mode.
fn trace_device_task_queue_failed(task: &str) {
    tracelogging::write_event!(
        PROVIDER,
        "TdrDeviceTaskQueueFailed",
        level(Error),
        str8("task", task)
    );
}

/// Which of `sessions` is STILL not recovered, judged by the lock-free
/// liveness mirror — never by the ring mutex, which a live frame worker
/// pins for its entire lifetime.
///
/// Every path that is about to depart a display calls this first. A session
/// that has gone since the duck started, or whose ring is ACTIVE/DEAD
/// again, is not in trouble and must not be departed: build 16's whole
/// acceptance bar is "NO MonitorDeparture across the window", and the
/// queue-to-execution gap on the effects worker is more than enough for the
/// OS to have re-assigned a swap chain in the meantime.
fn unrecovered_sessions(sessions: &[u64]) -> Vec<u64> {
    let shell = Shell::get();
    let monitors = shell.monitors.lock().unwrap();
    sessions
        .iter()
        .filter(|sid| {
            monitors
                .get(sid)
                .is_some_and(|rt| !rt.ring.live.settled())
        })
        .copied()
        .collect()
}

/// How many of `sessions` are publishing RIGHT NOW (worker live + ring
/// ACTIVE). Reported alongside every skip so a trace shows the arm was
/// declined because the display was healthy, not because it had vanished.
fn publishing_sessions(sessions: &[u64]) -> u64 {
    let shell = Shell::get();
    let monitors = shell.monitors.lock().unwrap();
    sessions
        .iter()
        .filter(|sid| monitors.get(sid).is_some_and(|rt| rt.ring.live.publishing()))
        .count() as u64
}

/// The GATED FALLBACK departure — build 14/15's behaviour, reached only
/// when the device-duck cannot be sustained (the long deadline expired, or
/// the poller could not be spawned). Departs the still-unrecovered members
/// of the duck's LUID-scoped set and drains the parked set immediately:
/// there is no recovery left to wait for, the budget is already spent.
///
/// Scoped, not `duck_all`: the duck was scoped to one adapter's LUID
/// precisely so a monitor on a healthy second GPU is not dragged into
/// another adapter's reset, and departing everything here would have thrown
/// that away at the one moment it mattered.
fn depart_fallback(epoch: u64, sessions: &[u64], reason: &str) {
    let shell = Shell::get();
    let (departed, skipped) = if shell.adapter_epoch() == epoch {
        let unrecovered = unrecovered_sessions(sessions);
        let skipped = (sessions.len() - unrecovered.len()) as u64;
        (monitors::duck_sessions(epoch, &unrecovered), skipped)
    } else {
        (0, 0)
    };
    let abandoned = abandon_ducked(reason);
    tracelogging::write_event!(
        PROVIDER,
        "TdrDeviceDuckGaveUp",
        level(Warning),
        str8("reason", reason),
        u64("departed", &(departed as u64)),
        u64("kept", &skipped),
        u64("abandoned", &abandoned)
    );
    finish_device_duck();
}

/// Device-duck entry point on the effects worker. Note what is ABSENT:
/// there is no `monitors::duck_all` call, and that omission is the whole
/// change. Everything the teardown needs already happened on the frame
/// worker (D3D device dropped at `frame_loop`'s return, swapchain
/// abandoned, textures retired with a generation bump, ring REBUILDING).
/// The IddCx monitor stays ARRIVED, so Windows keeps a display path and
/// no `DBT_DEVNODES_CHANGED` departure is broadcast.
fn run_tdr_device_duck(epoch: u64, session_id: u64, reason_hr: i32) {
    let shell = Shell::get();
    if shell.adapter_epoch() != epoch {
        finish_device_duck();
        tracelogging::write_event!(PROVIDER, "TdrDeviceDuckStale", level(Warning));
        return;
    }
    reset_cycles_if_new_incident();

    // Scope the duck to the adapter that actually reported removal: a
    // monitor rendering on a HEALTHY second adapter must not be dragged
    // into another GPU's reset. The poller judges each covered session by
    // its RING STATE, so nothing else needs snapshotting here.
    let (luid, sessions) = {
        let monitors = shell.monitors.lock().unwrap();
        // If the failing session is GONE, duck nothing: falling back to
        // luid 0 would sweep in every never-assigned monitor and then probe
        // a LUID that EnumAdapterByLuid cannot resolve, so the poller could
        // never see recovery and would burn the whole 10-minute budget
        // before departing displays that were never in trouble.
        match monitors.get(&session_id).map(|rt| rt.adapter_luid) {
            Some(luid) => {
                let sessions: Vec<u64> = monitors
                    .iter()
                    .filter(|(_, rt)| rt.adapter_luid == luid)
                    .map(|(sid, _)| *sid)
                    .collect();
                (luid, sessions)
            }
            None => (0, Vec::new()),
        }
    };
    if sessions.is_empty() {
        // Destroyed between the worker's failure and this task. Nothing to
        // keep alive, and deliberately consumes no incident budget.
        finish_device_duck();
        tracelogging::write_event!(
            PROVIDER,
            "TdrDeviceDuckNoMonitors",
            level(Informational),
            u64("session", &session_id)
        );
        return;
    }
    tracelogging::write_event!(
        PROVIDER,
        "TdrDeviceDuckStart",
        level(Warning),
        u64("session", &session_id),
        u64("sessions", &(sessions.len() as u64)),
        u64("luid", &luid),
        i32("hresult", &reason_hr)
    );

    // The poller lives on its own thread for the same reason the legacy
    // one does: the effects worker must stay free for every other IddCx
    // side effect while the GPU recovers.
    let poller_sessions = sessions.clone();
    let spawned = std::thread::Builder::new()
        .name("vgd-tdr-device".into())
        .spawn(move || device_duck_poller(epoch, luid, poller_sessions));
    if spawned.is_err() {
        // Without a poller there is no heartbeat and no recovery
        // detection, so an arrived monitor would sit behind a frozen ring
        // with nothing watching it. Take the fallback instead.
        tracelogging::write_event!(PROVIDER, "TdrDevicePollerSpawnFailed", level(Error));
        depart_fallback(epoch, &sessions, "poller spawn failed");
    }
}

/// The device-duck recovery poller. Every wait here is bounded and none of
/// it runs on a callback frame (§3.3): own thread, 250 ms tick, D3D probes
/// on THROWAWAY 15 s-deadline threads that are detached if they hang
/// inside a wedged OS call.
fn device_duck_poller(epoch: u64, luid: u64, sessions: Vec<u64>) {
    let shell = Shell::get();
    let started = std::time::Instant::now();
    let deadline = started + TDR_RECOVERY_BUDGET;
    let mut probe: Option<(std::thread::JoinHandle<bool>, std::time::Instant)> = None;
    let mut last_hang_at: Option<std::time::Instant> = None;
    let mut last_probe_step = std::time::Instant::now();
    let mut recovered_at: Option<std::time::Instant> = None;
    let mut heartbeat_blocked_traced = false;
    let mut heartbeats: u64 = 0;

    loop {
        std::thread::sleep(TDR_DEVICE_TICK);

        if shell.adapter_epoch() != epoch {
            // D3Final tore the device down. Its drain already handled these
            // monitors through the ordinary MonitorTornDown path — they
            // were never parked, which is exactly why nothing extra is
            // needed here (contrast the legacy poller, which must
            // `abandon_ducked` entries it still owns).
            tracelogging::write_event!(PROVIDER, "TdrDevicePollerStale", level(Informational));
            finish_device_duck();
            return;
        }

        // Snapshot the covered sessions' ring Arcs, then release the
        // monitors lock BEFORE touching any ring: `duck_all` takes
        // monitors→ring, so doing the same here keeps that order, and the
        // per-ring try_locks must not run under a lock IddCx callbacks
        // also take.
        let rings: Vec<(u64, std::sync::Arc<super::swapchain::RingHandle>)> = {
            let monitors = shell.monitors.lock().unwrap();
            sessions
                .iter()
                .filter_map(|sid| monitors.get(sid).map(|rt| (*sid, rt.ring.clone())))
                .collect()
        };
        if rings.is_empty() {
            tracelogging::write_event!(
                PROVIDER,
                "TdrDeviceDuckSessionsGone",
                level(Informational),
                u64("held_ms", &(started.elapsed().as_millis() as u64))
            );
            finish_device_duck();
            return;
        }
        // One tick per covered ring: decide recovery from the LOCK-FREE
        // liveness mirror, and refresh the heartbeat of whatever is still
        // REBUILDING. The mirror, not the ring mutex: `frame_loop` pins
        // that mutex for the entire life of a worker, so a fully recovered,
        // actively-publishing ring can NEVER grant a try_lock — asking the
        // lock first (build 16's first cut) made every genuine recovery
        // read as "still pending", put the good exit below out of reach,
        // and handed the display to the requalify arm ~10 s later. Only
        // `frame_loop` publishes ACTIVE, and only after
        // IddCxSwapChainSetDevice succeeded on a freshly created device, so
        // a replacement worker that died in create_device_on_luid (GPU
        // still gone) leaves the mirror REBUILDING and this poller
        // correctly keeps watching.
        let mut pending = 0usize;
        let mut live_gens = 0u64;
        for (_, ring) in &rings {
            live_gens += ring.live.live_generation();
            match super::ring_tick_arc(ring) {
                super::RingTick::Settled => {}
                super::RingTick::Rebuilding => {
                    pending += 1;
                    heartbeats += 1;
                }
                super::RingTick::HeartbeatBlocked => {
                    pending += 1;
                    if !heartbeat_blocked_traced {
                        // A deadline-DETACHED worker is pinning the ring
                        // mutex — the only way to reach this arm now that
                        // a live worker settles lock-free. Traced once per
                        // duck; the host's stale-heartbeat handling covers
                        // it exactly as it did before build 16.
                        heartbeat_blocked_traced = true;
                        tracelogging::write_event!(
                            PROVIDER,
                            "TdrDeviceHeartbeatBlocked",
                            level(Warning)
                        );
                    }
                }
            }
        }
        if pending == 0 {
            // THE GOOD EXIT: every covered ring is publishing again (or is
            // finished). The OS drove its own unassign→assign, the
            // transport is back with ZERO modesets from us, and the display
            // never left — which is the entire point of build 16.
            tracelogging::write_event!(
                PROVIDER,
                "TdrDeviceReassigned",
                level(Informational),
                u64("elapsed_ms", &(started.elapsed().as_millis() as u64)),
                u64("heartbeats", &heartbeats),
                // Total go-live transitions across the covered rings. Says
                // a worker really came back, as opposed to the rings never
                // having been REBUILDING in the first place.
                u64("live_gens", &live_gens),
                // Keeps this event honest: says whether our own probe ever
                // confirmed the GPU answering again, or whether the ring
                // simply went ACTIVE first. "Did it really come back?" is
                // the whole question a build-16 capture is taken to answer.
                u32("gpu_confirmed", &(recovered_at.is_some() as u32))
            );
            shell
                .tdr_last_recovery_ms
                .store(shell.now_ms().max(1), std::sync::atomic::Ordering::SeqCst);
            // Release the one-in-flight latch, THEN re-read the mirrors.
            // Between the tally above and this store, a worker can fail
            // again; its `queue_tdr_duck` would lose the CAS to the latch
            // we are about to clear and be dropped, leaving an arrived
            // monitor behind a REBUILDING ring with nothing watching it.
            // Clearing first and re-checking after closes that window in
            // the only order that can: anything that failed BEFORE the
            // clear is still visible in the mirror, and anything after it
            // arms itself.
            finish_device_duck();
            for (session_id, ring) in &rings {
                if !ring.live.settled() {
                    tracelogging::write_event!(
                        PROVIDER,
                        "TdrDeviceDuckRearmed",
                        level(Warning),
                        u64("session", session_id)
                    );
                    queue_tdr_duck(*session_id, 0);
                    break;
                }
            }
            return;
        }

        if last_probe_step.elapsed() >= TDR_RECOVERY_PROBE_EVERY {
            last_probe_step = std::time::Instant::now();
            if let Some((handle, at)) = probe.take() {
                if handle.is_finished() {
                    if handle.join().unwrap_or(false) && recovered_at.is_none() {
                        recovered_at = Some(std::time::Instant::now());
                        tracelogging::write_event!(
                            PROVIDER,
                            "TdrDeviceRecovered",
                            level(Informational),
                            u64("elapsed_ms", &(started.elapsed().as_millis() as u64))
                        );
                    }
                } else if at.elapsed() >= TDR_PROBE_DEADLINE {
                    // Hung inside the OS call — detach and rate-limit
                    // respawns. The leak is bounded by the respawn interval
                    // and each thread exits when its call finally returns.
                    drop(handle);
                    last_hang_at = Some(std::time::Instant::now());
                    tracelogging::write_event!(PROVIDER, "TdrRecoveryProbeHung", level(Warning));
                } else {
                    probe = Some((handle, at));
                }
            }
            if probe.is_none() && recovered_at.is_none() {
                let respawn_ok = match last_hang_at {
                    Some(at) => at.elapsed() >= TDR_PROBE_RESPAWN_AFTER_HANG,
                    None => true,
                };
                if respawn_ok {
                    if let Ok(handle) = std::thread::Builder::new()
                        .name("vgd-tdr-probe".into())
                        .spawn(move || super::swapchain::probe_adapter_on_luid(luid))
                    {
                        probe = Some((handle, std::time::Instant::now()));
                    }
                }
            }
        }

        if recovered_at.is_some_and(|at| at.elapsed() >= TDR_REASSIGN_GRACE) {
            // The GPU answers again but the OS never came back for the
            // swapchain. Force ONE depart+re-arrive — a clean modeset
            // against a stack we just probed HEALTHY, which is a
            // categorically different act from departing the last display
            // in the middle of a wedge.
            tracelogging::write_event!(
                PROVIDER,
                "TdrDeviceRequalifyQueued",
                level(Warning),
                u64("elapsed_ms", &(started.elapsed().as_millis() as u64))
            );
            // Only the sessions that are STILL unrecovered travel with the
            // task, and `run_tdr_requalify` re-checks them again before it
            // departs anything.
            let unrecovered = unrecovered_sessions(&sessions);
            if send_task(EffectsTask::TdrRequalify { epoch, sessions: unrecovered }).is_some() {
                // Effects worker gone (D3Final, or it never spawned). The
                // monitor stays ARRIVED — the safe residue in this mode, and
                // deliberately NOT an inline departure: an IddCx call from a
                // poller thread is exactly what §3.3 forbids.
                trace_device_task_queue_failed("requalify");
                finish_device_duck();
            }
            return;
        }

        if std::time::Instant::now() >= deadline {
            // Never recovered inside the budget: this is the machine-wide
            // wedge case, where only a reboot helps. Hand the fallback to
            // the effects worker (departure is an IddCx call and must be
            // ordered with every other side effect).
            let unrecovered = unrecovered_sessions(&sessions);
            if send_task(EffectsTask::TdrDeadlineDepart { epoch, sessions: unrecovered }).is_some()
            {
                trace_device_task_queue_failed("deadline depart");
                finish_device_duck();
            }
            return;
        }
    }
}

/// The "OS recovery genuinely completed" departure: depart + immediately
/// re-arrive, so Windows rebuilds the path against a healthy stack and
/// reattaches the remembered topology (same container GUID + connector).
fn run_tdr_requalify(epoch: u64, sessions: Vec<u64>) {
    let shell = Shell::get();
    if shell.adapter_epoch() != epoch {
        tracelogging::write_event!(PROVIDER, "TdrRequalifyStale", level(Warning));
        finish_device_duck();
        return;
    }
    // THE GUARD. This arm is the only thing in device-duck mode that can
    // take a display away, so it re-reads the lock-free liveness mirror
    // immediately before acting and departs NOTHING that has come back.
    // The poller already filtered, but this task sat on the effects queue
    // behind whatever else was in flight, and the OS re-assigns swap chains
    // on its own clock — "healthy and publishing" is a state that can
    // arrive at any point in that gap. Departing then would be the exact
    // failure build 16 exists to prevent (a modeset plus the
    // DBT_DEVNODES_CHANGED broadcast on a machine that already healed).
    let unrecovered = unrecovered_sessions(&sessions);
    if unrecovered.is_empty() {
        tracelogging::write_event!(
            PROVIDER,
            "TdrDeviceRequalifySkipped",
            level(Informational),
            u64("covered", &(sessions.len() as u64)),
            u64("publishing", &publishing_sessions(&sessions))
        );
        // A recovery, not a give-up: the display never left, so this counts
        // as the good outcome for the incident-window budget and consumes
        // no cycle.
        shell
            .tdr_last_recovery_ms
            .store(shell.now_ms().max(1), std::sync::atomic::Ordering::SeqCst);
        finish_device_duck();
        return;
    }
    // The requalify is the ONLY modeset build 16 performs, so this is what
    // the per-incident cycle budget governs in device-duck mode (in legacy
    // mode the same counter caps duck→replug flaps). A stack needing a
    // fourth forced modeset in one incident is flapping: stop churning and
    // leave the monitor arrived — an arrived-but-idle display is still a
    // display Windows can compose onto, which is the point.
    let cycle = shell.tdr_duck_cycles.fetch_add(1, std::sync::atomic::Ordering::SeqCst) + 1;
    if cycle > TDR_MAX_DUCK_CYCLES {
        tracelogging::write_event!(
            PROVIDER,
            "TdrRequalifyCapped",
            level(Warning),
            u32("cycle", &cycle)
        );
        finish_device_duck();
        return;
    }
    // Scoped to the duck's own unrecovered sessions — `duck_all` here would
    // depart monitors on a healthy second adapter and undo the per-LUID
    // scoping run_tdr_device_duck computed.
    let departed = monitors::duck_sessions(epoch, &unrecovered);
    tracelogging::write_event!(
        PROVIDER,
        "TdrDeviceRequalify",
        level(Warning),
        u64("departed", &(departed as u64)),
        u64("kept", &((sessions.len() - unrecovered.len()) as u64)),
        u32("cycle", &cycle)
    );
    if departed > 0 {
        monitors::replug_ducked();
        shell
            .tdr_last_recovery_ms
            .store(shell.now_ms().max(1), std::sync::atomic::Ordering::SeqCst);
    }
    finish_device_duck();
}

/// The "long deadline expired" departure (task spec's second clause).
/// `depart_fallback` re-checks the liveness mirror, so a session that came
/// back while this task sat on the queue is kept, not departed.
fn run_tdr_deadline_depart(epoch: u64, sessions: Vec<u64>) {
    if Shell::get().adapter_epoch() != epoch {
        tracelogging::write_event!(PROVIDER, "TdrDeadlineDepartStale", level(Warning));
        finish_device_duck();
        return;
    }
    depart_fallback(epoch, &sessions, "recovery deadline");
}

/// Adapter bring-up, off the EvtIddCxAdapterInitFinished frame: both the
/// DXGI factory walk (D3D work) and the permanent-pool replug (IddCx
/// monitor create/arrival) violate the callback rules when run inline.
/// The adapter handle is published (ready() flips true) only after
/// set_adapters + startup — the same ordering the inline version had, so
/// a CREATE_MONITOR racing bring-up still sees NOT_READY until the
/// adapter list exists. Epoch-guarded at both ends: a D3Final teardown
/// between queue and execution (or between startup and publication)
/// makes this a traced no-op instead of republishing a destroyed
/// adapter.
fn run_adapter_ready(adapter: OsHandle, epoch: u64) {
    let shell = Shell::get();
    if shell.adapter_epoch() != epoch {
        tracelogging::write_event!(PROVIDER, "AdapterReadyStale", level(Warning));
        return;
    }
    let adapters = dxgi::enumerate();
    let effects = {
        let mut dev = shell.dev.lock().unwrap();
        dev.set_adapters(adapters);
        dev.startup(shell.now_ms())
    };
    if !shell.set_adapter_if_epoch(adapter, epoch) {
        // Undo startup()'s table mutations: its pool sessions are
        // lease-disabled (the watchdog can never reap them) and their
        // monitors were never plugged — left in place they would brick
        // the next bring-up with DuplicateSession. Identity reservations
        // survive the reset.
        shell.dev.lock().unwrap().device_teardown_reset();
        tracelogging::write_event!(PROVIDER, "AdapterReadyStale", level(Warning));
        return;
    }
    apply_now(effects);
    tracelogging::write_event!(PROVIDER, "AdapterReady", level(Informational));
}

/// Apply dispatcher side effects. Runs on the effects worker (or the
/// traced inline fallback). Called with NO locks held — plugging and
/// unplugging call into IddCx (DESIGN.md §3.3 rule 3).
fn apply_now(effects: Vec<Effect>) {
    for effect in effects {
        match effect {
            Effect::PlugMonitor {
                session_id,
                display_id,
                connector_index,
                modes,
                adapter_luid,
                ring_slots,
                edid,
            } => monitors::plug(
                session_id,
                display_id,
                connector_index,
                modes,
                adapter_luid,
                ring_slots,
                edid,
            ),
            Effect::UnplugMonitor { session_id } => monitors::unplug(session_id),
            Effect::PersistState(blob) => unsafe { write_persisted(&blob) },
        }
    }
}

/// Session-mutating IOCTLs are refused until the IddCx adapter is up
/// (dispatch would accept them, but the plug effect could not be applied).
fn requires_adapter(code: u32) -> bool {
    matches!(
        code,
        ioctl::IOCTL_CREATE_MONITOR
            | ioctl::IOCTL_DESTROY_MONITOR
            | ioctl::IOCTL_SET_PERMANENT_POOL
    )
}

pub unsafe extern "C" fn evt_ioctl(
    _device: WDFDEVICE,
    request: WDFREQUEST,
    output_len: usize,
    input_len: usize,
    code: ULONG,
) {
    let shell = Shell::get();

    // §6 control-surface ACL: only callers that pass the
    // SYSTEM/Administrators check may issue IOCTLs. Handles authorized at
    // file-create skip straight through; any other handle gets the same
    // token check re-evaluated HERE, against the IOCTL's own caller. The
    // lazy re-check exists because build 8 authorized only at create and
    // production service callers ended up with unauthorized handles (open
    // succeeded, every IOCTL denied, nothing traced) — no single
    // create-time quirk may ever brick a legitimate SYSTEM caller again.
    // Fail closed: refused or unevaluable callers are denied either way.
    let file_key =
        call_unsafe_wdf_function_binding!(WdfRequestGetFileObject, request) as usize;
    let authorized = shell
        .handles
        .lock()
        .unwrap()
        .get(&file_key)
        .map(|h| h.authorized)
        .unwrap_or(false);
    if !authorized {
        match authorize_request(request) {
            AuthOutcome::Authorized { how } => {
                let mut handles = shell.handles.lock().unwrap();
                handles.entry(file_key).or_insert_with(HandleCtx::default).authorized = true;
                tracelogging::write_event!(
                    PROVIDER,
                    "IoctlAuthorizedLate",
                    level(Informational),
                    u32("ioctl", &code),
                    u32("how", &how)
                );
            }
            AuthOutcome::Refused => {
                tracelogging::write_event!(
                    PROVIDER,
                    "IoctlDenied",
                    level(Warning),
                    u32("ioctl", &code),
                    u32("stage", &STAGE_POLICY),
                    u32("code", &0u32)
                );
                call_unsafe_wdf_function_binding!(
                    WdfRequestComplete,
                    request,
                    STATUS_ACCESS_DENIED
                );
                return;
            }
            AuthOutcome::Unavailable { stage, code: err } => {
                tracelogging::write_event!(
                    PROVIDER,
                    "IoctlDenied",
                    level(Warning),
                    u32("ioctl", &code),
                    u32("stage", &stage),
                    u32("code", &err)
                );
                call_unsafe_wdf_function_binding!(
                    WdfRequestComplete,
                    request,
                    STATUS_ACCESS_DENIED
                );
                return;
            }
        }
    }

    if requires_adapter(code) && !shell.ready() {
        call_unsafe_wdf_function_binding!(WdfRequestComplete, request, STATUS_DEVICE_NOT_READY);
        return;
    }

    let mut in_ptr: PVOID = null_mut();
    let mut in_got: usize = 0;
    if input_len > 0 {
        let status = call_unsafe_wdf_function_binding!(
            WdfRequestRetrieveInputBuffer,
            request,
            0,
            &mut in_ptr,
            &mut in_got
        );
        if status != STATUS_SUCCESS {
            call_unsafe_wdf_function_binding!(WdfRequestComplete, request, status);
            return;
        }
    }
    let mut out_ptr: PVOID = null_mut();
    let mut out_got: usize = 0;
    if output_len > 0 {
        let status = call_unsafe_wdf_function_binding!(
            WdfRequestRetrieveOutputBuffer,
            request,
            0,
            &mut out_ptr,
            &mut out_got
        );
        if status != STATUS_SUCCESS {
            call_unsafe_wdf_function_binding!(WdfRequestComplete, request, status);
            return;
        }
    }

    let input: &[u8] = if in_got > 0 {
        core::slice::from_raw_parts(in_ptr.cast::<u8>(), in_got)
    } else {
        &[]
    };
    let output: &mut [u8] = if out_got > 0 {
        core::slice::from_raw_parts_mut(out_ptr.cast::<u8>(), out_got)
    } else {
        &mut []
    };

    let result = {
        let mut handles = shell.handles.lock().unwrap();
        let handle = handles.entry(file_key).or_insert_with(HandleCtx::default);
        let mut dev = shell.dev.lock().unwrap();
        dispatch(&mut dev, handle, shell.now_ms(), code, input, output)
    };

    let (status, info): (NTSTATUS, usize) = match result.status {
        Status::Ok => (STATUS_SUCCESS, result.bytes_written),
        Status::BadBuffer => (STATUS_INVALID_PARAMETER, 0),
        Status::UnknownCode => (STATUS_INVALID_DEVICE_REQUEST, 0),
    };
    call_unsafe_wdf_function_binding!(
        WdfRequestCompleteWithInformation,
        request,
        status,
        info as u64
    );

    // OS work strictly after request completion — queued to the effects
    // worker, never applied on this IddCx callback frame.
    queue_effects(result.effects);
}

pub unsafe extern "C" fn evt_file_create(
    _device: WDFDEVICE,
    request: WDFREQUEST,
    file_object: WDFFILEOBJECT,
) {
    // Which name is this open using? Interface opens through our control
    // symlink carry the reference string; the OS graphics stack's opens
    // of the same device object carry other (usually empty) names and
    // must pass unhindered (phase-2 lesson: they run unelevated).
    let name_ptr = call_unsafe_wdf_function_binding!(WdfFileObjectGetFileName, file_object);
    let name: &[u16] = if name_ptr.is_null() {
        &[]
    } else {
        let n = &*name_ptr;
        if n.Buffer.is_null() {
            &[]
        } else {
            core::slice::from_raw_parts(n.Buffer, (n.Length / 2) as usize)
        }
    };

    if !is_control_name(name) {
        // Not the control plane: allow, unauthorized (IOCTLs are refused).
        if let Some(shell) = Shell::try_get() {
            shell
                .handles
                .lock()
                .unwrap()
                .insert(file_object as usize, HandleCtx::default());
        }
        call_unsafe_wdf_function_binding!(WdfRequestComplete, request, STATUS_SUCCESS);
        return;
    }

    // Control-plane open: DESIGN.md §6 — SYSTEM or elevated Administrators
    // only. Refused callers fail the open (fail closed). When the token
    // CANNOT be evaluated (impersonation machinery, not policy), the open
    // is allowed but UNAUTHORIZED: every IOCTL then re-runs the same check
    // against its own caller, so a create-time evaluation quirk cannot
    // permanently brick a legitimate SYSTEM caller — and an illegitimate
    // one still cannot issue a single IOCTL.
    match authorize_request(request) {
        AuthOutcome::Authorized { how } => {
            tracelogging::write_event!(
                PROVIDER,
                "ControlOpenAuthorized",
                level(Informational),
                u32("how", &how)
            );
            if let Some(shell) = Shell::try_get() {
                shell.handles.lock().unwrap().insert(
                    file_object as usize,
                    HandleCtx { authorized: true, ..HandleCtx::default() },
                );
            }
            call_unsafe_wdf_function_binding!(WdfRequestComplete, request, STATUS_SUCCESS);
        }
        AuthOutcome::Refused => {
            tracelogging::write_event!(
                PROVIDER,
                "ControlOpenDenied",
                level(Warning),
                u32("stage", &STAGE_POLICY),
                u32("code", &0u32)
            );
            call_unsafe_wdf_function_binding!(WdfRequestComplete, request, STATUS_ACCESS_DENIED);
        }
        AuthOutcome::Unavailable { stage, code } => {
            tracelogging::write_event!(
                PROVIDER,
                "ControlOpenAuthUnavailable",
                level(Warning),
                u32("stage", &stage),
                u32("code", &code)
            );
            if let Some(shell) = Shell::try_get() {
                shell
                    .handles
                    .lock()
                    .unwrap()
                    .insert(file_object as usize, HandleCtx::default());
            }
            call_unsafe_wdf_function_binding!(WdfRequestComplete, request, STATUS_SUCCESS);
        }
    }
}

pub unsafe extern "C" fn evt_file_close(file_object: WDFFILEOBJECT) {
    if let Some(shell) = Shell::try_get() {
        shell.handles.lock().unwrap().remove(&(file_object as usize));
    }
}
