// SPDX-License-Identifier: AGPL-3.0-only
//! Control plane: EvtIddCxDeviceIoControl → [`crate::dispatch::dispatch`],
//! effect application, per-handle contexts, and registry persistence.

use core::ptr::null_mut;
use core::sync::atomic::{AtomicU32, Ordering};

use wdk_sys::{
    call_unsafe_wdf_function_binding, NTSTATUS, PVOID, STATUS_DEVICE_NOT_READY,
    STATUS_INVALID_DEVICE_REQUEST, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, ULONG,
    UNICODE_STRING, WDFDEVICE, WDFFILEOBJECT, WDFKEY, WDFREQUEST,
};
use windows::Win32::Foundation::{CloseHandle, GetLastError, HANDLE};
use windows::Win32::Security::{
    CheckTokenMembership, CreateWellKnownSid, EqualSid, GetTokenInformation, TokenGroups,
    TokenUser, WinBuiltinAdministratorsSid, WinLocalSystemSid, PSID, SECURITY_MAX_SID_SIZE,
    TOKEN_GROUPS, TOKEN_QUERY, TOKEN_USER, WELL_KNOWN_SID_TYPE,
};
use windows::Win32::System::Threading::{GetCurrentThread, OpenThreadToken};

/// `SE_GROUP_ENABLED` (winnt.h) — not generated by the `windows` crate's
/// `Win32_Security` feature set.
const SE_GROUP_ENABLED: u32 = 0x0000_0004;

use std::sync::mpsc;

use super::PROVIDER;
use super::{dxgi, monitors, OsHandle, Shell};
use crate::dispatch::{dispatch, Effect, HandleCtx, Status};
use luminal_driver_proto::ioctl;

const STATUS_ACCESS_DENIED: NTSTATUS = 0xC000_0022u32 as NTSTATUS;

/// Reference string of the control device interface. Opens through the
/// enumerated interface symlink carry `\LuminalVGDControl` as the file
/// name; that name (and only that name) is subject to the DESIGN.md §6
/// SYSTEM+Administrators check below.
static CONTROL_REF: [u16; 18] = super::wide("LuminalVGDControl");

pub(crate) fn control_ref_unicode() -> UNICODE_STRING {
    let bytes = ((CONTROL_REF.len() - 1) * 2) as u16;
    UNICODE_STRING {
        Length: bytes,
        MaximumLength: bytes + 2,
        Buffer: CONTROL_REF.as_ptr().cast_mut(),
    }
}

/// Case-insensitive check whether `name` (a file-object name) addresses
/// the control interface: `\LuminalVGDControl` with or without the
/// leading backslash.
fn is_control_name(name: &[u16]) -> bool {
    let want = &CONTROL_REF[..CONTROL_REF.len() - 1]; // strip NUL
    let name = if name.first() == Some(&(b'\\' as u16)) { &name[1..] } else { name };
    name.len() == want.len()
        && name
            .iter()
            .zip(want.iter())
            .all(|(&a, &b)| char_fold(a) == char_fold(b))
}

fn char_fold(c: u16) -> u16 {
    match c {
        0x61..=0x7A => c - 0x20, // a-z → A-Z (the ref string is ASCII)
        _ => c,
    }
}

fn well_known_sid(kind: WELL_KNOWN_SID_TYPE, buf: &mut [u8; SECURITY_MAX_SID_SIZE as usize]) -> Option<PSID> {
    let mut len = buf.len() as u32;
    unsafe {
        CreateWellKnownSid(kind, None, Some(PSID(buf.as_mut_ptr().cast())), &mut len).ok()?;
    }
    Some(PSID(buf.as_mut_ptr().cast()))
}

// Stages of the §6 authorization check, traced verbatim on every failure
// so a single ETW capture localizes a denial without a re-sign round
// (lesson from build 8: the check had exactly one untraceable deny path,
// and the installed-service context tripped it with zero diagnostics).
const STAGE_POLICY: u32 = 0; // check ran to completion; caller not SYSTEM/admin
const STAGE_IMPERSONATE: u32 = 1; // WdfRequestImpersonate failed (code = NTSTATUS)
const STAGE_OPEN_TOKEN: u32 = 2; // OpenThreadToken failed (code = Win32 error)
const STAGE_QUERY_USER: u32 = 3; // GetTokenInformation(TokenUser) failed
const STAGE_QUERY_GROUPS: u32 = 4; // GetTokenInformation(TokenGroups) failed
const STAGE_SID: u32 = 5; // CreateWellKnownSid failed
const STAGE_CHECK_MEMBERSHIP: u32 = 6; // CheckTokenMembership fallback failed

const OUTCOME_UNSET: u32 = 0;
const OUTCOME_SYSTEM: u32 = 1;
const OUTCOME_ADMIN: u32 = 2;
const OUTCOME_REFUSED: u32 = 3;

/// Result of evaluating the DESIGN.md §6 policy against a request's caller.
#[derive(Clone, Copy, Debug)]
pub(crate) enum AuthOutcome {
    /// Caller's token inspected: SYSTEM (`how` 1) or an elevated
    /// Administrator (`how` 2).
    Authorized { how: u32 },
    /// Caller's token inspected; it is neither. Fail closed.
    Refused,
    /// The token could not be evaluated at all (stage/code say where).
    /// The policy question is unanswered — never treat as authorized.
    Unavailable { stage: u32, code: u32 },
}

/// Filled by [`evt_impersonate`] while the caller's token is on the thread.
struct AuthProbe {
    outcome: AtomicU32,
    stage: AtomicU32,
    code: AtomicU32,
}

impl AuthProbe {
    const fn new() -> Self {
        Self {
            outcome: AtomicU32::new(OUTCOME_UNSET),
            stage: AtomicU32::new(0),
            code: AtomicU32::new(0),
        }
    }

    /// Record the FIRST failing stage only — later fallback attempts must
    /// not overwrite the diagnosis of where the primary path broke.
    fn fail(&self, stage: u32, code: u32) {
        if self
            .stage
            .compare_exchange(0, stage, Ordering::AcqRel, Ordering::Acquire)
            .is_ok()
        {
            self.code.store(code, Ordering::Release);
        }
    }
}

/// Direct token inspection: the token's *user* SID must be LocalSystem, or
/// its group list must carry BUILTIN\Administrators with `SE_GROUP_ENABLED`.
/// A filtered (non-elevated) admin token carries that SID deny-only —
/// without the enabled attribute — so it is correctly refused. Deliberately
/// no `CheckTokenMembership`/`AccessCheck`: build 8 used it and production
/// service callers were refused with no way to tell why; plain
/// `GetTokenInformation` + `EqualSid` has no hidden evaluation semantics.
unsafe fn inspect_token(token: HANDLE, probe: &AuthProbe) {
    // 8-aligned buffers: TOKEN_USER embeds pointers.
    let mut user_buf = [0u64; (SECURITY_MAX_SID_SIZE as usize + 32).div_ceil(8)];
    let mut ret_len = 0u32;
    if GetTokenInformation(
        token,
        TokenUser,
        Some(user_buf.as_mut_ptr().cast()),
        (user_buf.len() * 8) as u32,
        &mut ret_len,
    )
    .is_err()
    {
        probe.fail(STAGE_QUERY_USER, GetLastError().0);
        return;
    }
    let user_sid = (*(user_buf.as_ptr() as *const TOKEN_USER)).User.Sid;

    let mut sid_buf = [0u8; SECURITY_MAX_SID_SIZE as usize];
    let Some(system) = well_known_sid(WinLocalSystemSid, &mut sid_buf) else {
        probe.fail(STAGE_SID, GetLastError().0);
        return;
    };
    if EqualSid(user_sid, system).is_ok() {
        probe.outcome.store(OUTCOME_SYSTEM, Ordering::Release);
        return;
    }

    let mut need = 0u32;
    let _ = GetTokenInformation(token, TokenGroups, None, 0, &mut need);
    if need == 0 {
        probe.fail(STAGE_QUERY_GROUPS, GetLastError().0);
        return;
    }
    let mut groups_buf = vec![0u64; (need as usize).div_ceil(8)];
    if GetTokenInformation(
        token,
        TokenGroups,
        Some(groups_buf.as_mut_ptr().cast()),
        (groups_buf.len() * 8) as u32,
        &mut ret_len,
    )
    .is_err()
    {
        probe.fail(STAGE_QUERY_GROUPS, GetLastError().0);
        return;
    }
    let Some(admins) = well_known_sid(WinBuiltinAdministratorsSid, &mut sid_buf) else {
        probe.fail(STAGE_SID, GetLastError().0);
        return;
    };
    let groups = &*(groups_buf.as_ptr() as *const TOKEN_GROUPS);
    let entries =
        core::slice::from_raw_parts(groups.Groups.as_ptr(), groups.GroupCount as usize);
    for group in entries {
        if (group.Attributes & SE_GROUP_ENABLED) != 0 && EqualSid(group.Sid, admins).is_ok() {
            probe.outcome.store(OUTCOME_ADMIN, Ordering::Release);
            return;
        }
    }
    probe.outcome.store(OUTCOME_REFUSED, Ordering::Release);
}

/// Runs inside `WdfRequestImpersonate` with the caller's token on the
/// thread. Ladder, because no single token-access path works in every
/// deployment (build 9 lesson — WUDFHost's account gates what it can open):
///
/// 1. `OpenThreadToken(OpenAsSelf=FALSE)` — access-checked as the client;
///    works at SecurityImpersonation (SYSTEM can always open SYSTEM's
///    token) but not at Identification (such tokens can't be used for
///    access checks).
/// 2. `OpenThreadToken(OpenAsSelf=TRUE)` — access-checked as the WUDFHost
///    account; works when the client token's DACL grants it.
/// 3. `CheckTokenMembership(NULL, …)` — the documented service-side
///    pattern for evaluating an impersonated client without managing a
///    token handle.
///
/// Every failed rung records its stage+code (first failure wins) so a
/// trace shows exactly which paths this machine refuses.
unsafe extern "C" fn evt_impersonate(_request: WDFREQUEST, context: PVOID) {
    let probe = &*(context as *const AuthProbe);
    let mut token = HANDLE::default();
    let mut opened =
        OpenThreadToken(GetCurrentThread(), TOKEN_QUERY, false, &mut token).is_ok();
    if !opened {
        probe.fail(STAGE_OPEN_TOKEN, GetLastError().0);
        opened = OpenThreadToken(GetCurrentThread(), TOKEN_QUERY, true, &mut token).is_ok();
    }
    if opened {
        inspect_token(token, probe);
        let _ = CloseHandle(token);
        if probe.outcome.load(Ordering::Acquire) != OUTCOME_UNSET {
            return;
        }
    }

    // Rung 3: direct membership checks on the thread token. Only a run in
    // which every rung answered (no errors) may conclude "refused".
    let mut sid_buf = [0u8; SECURITY_MAX_SID_SIZE as usize];
    let mut definitive = true;
    for (kind, outcome) in
        [(WinLocalSystemSid, OUTCOME_SYSTEM), (WinBuiltinAdministratorsSid, OUTCOME_ADMIN)]
    {
        let Some(sid) = well_known_sid(kind, &mut sid_buf) else {
            probe.fail(STAGE_SID, GetLastError().0);
            definitive = false;
            continue;
        };
        let mut member = windows::Win32::Foundation::FALSE;
        match CheckTokenMembership(None, sid, &mut member) {
            Ok(()) if member.as_bool() => {
                probe.outcome.store(outcome, Ordering::Release);
                return;
            }
            Ok(()) => {}
            Err(_) => {
                probe.fail(STAGE_CHECK_MEMBERSHIP, GetLastError().0);
                definitive = false;
            }
        }
    }
    if definitive {
        probe.outcome.store(OUTCOME_REFUSED, Ordering::Release);
    }
}

/// Evaluate the §6 policy against the caller of `request` (any request
/// type — creates and IOCTLs both carry the client identity in UMDF).
/// Prefers SecurityImpersonation (lets rung 1 work); falls back to
/// SecurityIdentification for clients that granted less at open.
pub(crate) unsafe fn authorize_request(request: WDFREQUEST) -> AuthOutcome {
    let probe = AuthProbe::new();
    let mut status = call_unsafe_wdf_function_binding!(
        WdfRequestImpersonate,
        request,
        wdk_sys::_SECURITY_IMPERSONATION_LEVEL::SecurityImpersonation,
        Some(evt_impersonate),
        (&probe as *const AuthProbe) as PVOID
    );
    if status != STATUS_SUCCESS {
        probe.fail(STAGE_IMPERSONATE, status as u32);
        status = call_unsafe_wdf_function_binding!(
            WdfRequestImpersonate,
            request,
            wdk_sys::_SECURITY_IMPERSONATION_LEVEL::SecurityIdentification,
            Some(evt_impersonate),
            (&probe as *const AuthProbe) as PVOID
        );
    }
    if status != STATUS_SUCCESS {
        return AuthOutcome::Unavailable {
            stage: STAGE_IMPERSONATE,
            code: probe.code.load(Ordering::Acquire),
        };
    }
    match probe.outcome.load(Ordering::Acquire) {
        how @ (OUTCOME_SYSTEM | OUTCOME_ADMIN) => AuthOutcome::Authorized { how },
        OUTCOME_REFUSED => AuthOutcome::Refused,
        _ => AuthOutcome::Unavailable {
            stage: probe.stage.load(Ordering::Acquire),
            code: probe.code.load(Ordering::Acquire),
        },
    }
}

/// Registry value under the device hardware key holding the persisted
/// state blob (identity reservations + permanent pool).
static VALUE_NAME: [u16; 16] = super::wide("LuminalVgdState");

fn value_name_unicode() -> UNICODE_STRING {
    let bytes = ((VALUE_NAME.len() - 1) * 2) as u16;
    UNICODE_STRING {
        Length: bytes,
        MaximumLength: bytes + 2,
        Buffer: VALUE_NAME.as_ptr().cast_mut(),
    }
}

const PLUGPLAY_REGKEY_DEVICE: ULONG = 1;
const KEY_READ_ACCESS: u32 = 0x2001_9; // KEY_READ
const KEY_WRITE_ACCESS: u32 = 0x2000_6; // KEY_WRITE
const REG_BINARY_TYPE: ULONG = 3;

unsafe fn open_device_key(device: WDFDEVICE, access: u32) -> Option<WDFKEY> {
    let mut key: WDFKEY = null_mut();
    let status = call_unsafe_wdf_function_binding!(
        WdfDeviceOpenRegistryKey,
        device,
        PLUGPLAY_REGKEY_DEVICE,
        access,
        wdk_sys::WDF_NO_OBJECT_ATTRIBUTES,
        &mut key
    );
    (status == STATUS_SUCCESS).then_some(key)
}

/// Read the persisted blob at device add (before the shell global
/// exists). Any failure is "no state" — parsing is defensive anyway.
pub unsafe fn read_persisted(device: WDFDEVICE) -> Option<Vec<u8>> {
    let key = open_device_key(device, KEY_READ_ACCESS)?;
    let name = value_name_unicode();
    let mut buf = vec![0u8; 4096];
    let mut got: ULONG = 0;
    let mut vtype: ULONG = 0;
    let status = call_unsafe_wdf_function_binding!(
        WdfRegistryQueryValue,
        key,
        &name,
        buf.len() as ULONG,
        buf.as_mut_ptr().cast::<core::ffi::c_void>(),
        &mut got,
        &mut vtype
    );
    call_unsafe_wdf_function_binding!(WdfRegistryClose, key);
    if status != STATUS_SUCCESS || vtype != REG_BINARY_TYPE || got == 0 {
        return None;
    }
    buf.truncate(got as usize);
    Some(buf)
}

unsafe fn write_persisted(blob: &[u8]) {
    let shell = Shell::get();
    let Some(device) = shell.wdf_device() else {
        // Device already tore down (clear_wdf_device at D3Final): the
        // write is dropped, not applied to a destroyed handle. Traced —
        // the next start re-reads the previous blob.
        tracelogging::write_event!(PROVIDER, "PersistSkippedNoDevice", level(Warning));
        return;
    };
    let Some(key) = open_device_key(device.0.cast(), KEY_WRITE_ACCESS) else {
        return;
    };
    let name = value_name_unicode();
    let status = call_unsafe_wdf_function_binding!(
        WdfRegistryAssignValue,
        key,
        &name,
        REG_BINARY_TYPE,
        blob.len() as ULONG,
        blob.as_ptr().cast::<core::ffi::c_void>().cast_mut()
    );
    call_unsafe_wdf_function_binding!(WdfRegistryClose, key);
    if status != STATUS_SUCCESS {
        tracelogging::write_event!(
            PROVIDER,
            "PersistFailed",
            level(Error),
            i32("status", &status)
        );
    }
}

/// Work items for the effects worker thread. Everything here calls into
/// IddCx and/or D3D, which must never happen on an IddCx callback or WDF
/// timer frame — those are win32k callouts, and calling back in deadlocks
/// against the locks win32k holds while calling us (0x1b8 storms,
/// builds 6/7; see CLAUDE.md).
pub(crate) enum EffectsTask {
    Apply(Vec<Effect>),
    /// Deferred EvtIddCxAdapterInitFinished bring-up: the DXGI walk,
    /// DeviceState::startup (permanent-pool replug), then publishing the
    /// adapter handle — which flips Shell::ready and un-gates session
    /// IOCTLs, in exactly that order. `epoch` was captured at queue time;
    /// a D3Final teardown in between bumps it, and the stale task must
    /// then do nothing (the adapter object it carries is destroyed).
    AdapterReady { adapter: OsHandle, epoch: u64 },
}

/// Spawn the effects worker at device add (from Shell::init). Returns
/// None on spawn failure; the queue functions then apply inline (the
/// pre-worker behavior) rather than dropping effects.
pub(crate) fn start_effects_thread() -> Option<mpsc::Sender<EffectsTask>> {
    let (tx, rx) = mpsc::channel::<EffectsTask>();
    let spawned = std::thread::Builder::new().name("vgd-effects".into()).spawn(move || {
        tracelogging::write_event!(PROVIDER, "EffectsWorkerSpawned", level(Informational));
        for task in rx {
            match task {
                EffectsTask::Apply(effects) => apply_now(effects),
                EffectsTask::AdapterReady { adapter, epoch } => {
                    run_adapter_ready(adapter, epoch)
                }
            }
        }
    });
    match spawned {
        Ok(_) => Some(tx),
        Err(_) => {
            tracelogging::write_event!(PROVIDER, "EffectsWorkerSpawnFailed", level(Error));
            None
        }
    }
}

/// Hand `task` to the effects worker. Returns the task back if the worker
/// is unavailable (never spawned, or its receiver is gone) so the caller
/// can fall back inline — a send error round-trips the same value.
fn send_task(task: EffectsTask) -> Option<EffectsTask> {
    let shell = Shell::get();
    let guard = shell.effects_tx.lock().unwrap();
    match guard.as_ref() {
        Some(tx) => match tx.send(task) {
            Ok(()) => None,
            Err(mpsc::SendError(task)) => Some(task),
        },
        None => Some(task),
    }
}

/// Queue dispatcher side effects for the effects worker (FIFO across all
/// producers). Callers may hold no locks the worker also takes; the send
/// itself never blocks. Inline fallback (traced) if the worker is gone —
/// effects must never be silently dropped.
pub(crate) fn queue_effects(effects: Vec<Effect>) {
    if effects.is_empty() {
        return;
    }
    if let Some(EffectsTask::Apply(effects)) = send_task(EffectsTask::Apply(effects)) {
        tracelogging::write_event!(PROVIDER, "EffectsInlineFallback", level(Warning));
        apply_now(effects);
    }
}

/// Queue the deferred adapter bring-up (EvtIddCxAdapterInitFinished).
pub(crate) fn queue_adapter_ready(adapter: OsHandle, epoch: u64) {
    if let Some(EffectsTask::AdapterReady { adapter, epoch }) =
        send_task(EffectsTask::AdapterReady { adapter, epoch })
    {
        tracelogging::write_event!(PROVIDER, "EffectsInlineFallback", level(Warning));
        run_adapter_ready(adapter, epoch);
    }
}

/// Adapter bring-up, off the EvtIddCxAdapterInitFinished frame: both the
/// DXGI factory walk (D3D work) and the permanent-pool replug (IddCx
/// monitor create/arrival) violate the callback rules when run inline.
/// The adapter handle is published (ready() flips true) only after
/// set_adapters + startup — the same ordering the inline version had, so
/// a CREATE_MONITOR racing bring-up still sees NOT_READY until the
/// adapter list exists. Epoch-guarded at both ends: a D3Final teardown
/// between queue and execution (or between startup and publication)
/// makes this a traced no-op instead of republishing a destroyed
/// adapter.
fn run_adapter_ready(adapter: OsHandle, epoch: u64) {
    let shell = Shell::get();
    if shell.adapter_epoch() != epoch {
        tracelogging::write_event!(PROVIDER, "AdapterReadyStale", level(Warning));
        return;
    }
    let adapters = dxgi::enumerate();
    let effects = {
        let mut dev = shell.dev.lock().unwrap();
        dev.set_adapters(adapters);
        dev.startup(shell.now_ms())
    };
    if !shell.set_adapter_if_epoch(adapter, epoch) {
        // Undo startup()'s table mutations: its pool sessions are
        // lease-disabled (the watchdog can never reap them) and their
        // monitors were never plugged — left in place they would brick
        // the next bring-up with DuplicateSession. Identity reservations
        // survive the reset.
        shell.dev.lock().unwrap().device_teardown_reset();
        tracelogging::write_event!(PROVIDER, "AdapterReadyStale", level(Warning));
        return;
    }
    apply_now(effects);
    tracelogging::write_event!(PROVIDER, "AdapterReady", level(Informational));
}

/// Apply dispatcher side effects. Runs on the effects worker (or the
/// traced inline fallback). Called with NO locks held — plugging and
/// unplugging call into IddCx (DESIGN.md §3.3 rule 3).
fn apply_now(effects: Vec<Effect>) {
    for effect in effects {
        match effect {
            Effect::PlugMonitor {
                session_id,
                display_id,
                connector_index,
                modes,
                adapter_luid,
                ring_slots,
                edid,
            } => monitors::plug(
                session_id,
                display_id,
                connector_index,
                modes,
                adapter_luid,
                ring_slots,
                edid,
            ),
            Effect::UnplugMonitor { session_id } => monitors::unplug(session_id),
            Effect::PersistState(blob) => unsafe { write_persisted(&blob) },
        }
    }
}

/// Session-mutating IOCTLs are refused until the IddCx adapter is up
/// (dispatch would accept them, but the plug effect could not be applied).
fn requires_adapter(code: u32) -> bool {
    matches!(
        code,
        ioctl::IOCTL_CREATE_MONITOR
            | ioctl::IOCTL_DESTROY_MONITOR
            | ioctl::IOCTL_SET_PERMANENT_POOL
    )
}

pub unsafe extern "C" fn evt_ioctl(
    _device: WDFDEVICE,
    request: WDFREQUEST,
    output_len: usize,
    input_len: usize,
    code: ULONG,
) {
    let shell = Shell::get();

    // §6 control-surface ACL: only callers that pass the
    // SYSTEM/Administrators check may issue IOCTLs. Handles authorized at
    // file-create skip straight through; any other handle gets the same
    // token check re-evaluated HERE, against the IOCTL's own caller. The
    // lazy re-check exists because build 8 authorized only at create and
    // production service callers ended up with unauthorized handles (open
    // succeeded, every IOCTL denied, nothing traced) — no single
    // create-time quirk may ever brick a legitimate SYSTEM caller again.
    // Fail closed: refused or unevaluable callers are denied either way.
    let file_key =
        call_unsafe_wdf_function_binding!(WdfRequestGetFileObject, request) as usize;
    let authorized = shell
        .handles
        .lock()
        .unwrap()
        .get(&file_key)
        .map(|h| h.authorized)
        .unwrap_or(false);
    if !authorized {
        match authorize_request(request) {
            AuthOutcome::Authorized { how } => {
                let mut handles = shell.handles.lock().unwrap();
                handles.entry(file_key).or_insert_with(HandleCtx::default).authorized = true;
                tracelogging::write_event!(
                    PROVIDER,
                    "IoctlAuthorizedLate",
                    level(Informational),
                    u32("ioctl", &code),
                    u32("how", &how)
                );
            }
            AuthOutcome::Refused => {
                tracelogging::write_event!(
                    PROVIDER,
                    "IoctlDenied",
                    level(Warning),
                    u32("ioctl", &code),
                    u32("stage", &STAGE_POLICY),
                    u32("code", &0u32)
                );
                call_unsafe_wdf_function_binding!(
                    WdfRequestComplete,
                    request,
                    STATUS_ACCESS_DENIED
                );
                return;
            }
            AuthOutcome::Unavailable { stage, code: err } => {
                tracelogging::write_event!(
                    PROVIDER,
                    "IoctlDenied",
                    level(Warning),
                    u32("ioctl", &code),
                    u32("stage", &stage),
                    u32("code", &err)
                );
                call_unsafe_wdf_function_binding!(
                    WdfRequestComplete,
                    request,
                    STATUS_ACCESS_DENIED
                );
                return;
            }
        }
    }

    if requires_adapter(code) && !shell.ready() {
        call_unsafe_wdf_function_binding!(WdfRequestComplete, request, STATUS_DEVICE_NOT_READY);
        return;
    }

    let mut in_ptr: PVOID = null_mut();
    let mut in_got: usize = 0;
    if input_len > 0 {
        let status = call_unsafe_wdf_function_binding!(
            WdfRequestRetrieveInputBuffer,
            request,
            0,
            &mut in_ptr,
            &mut in_got
        );
        if status != STATUS_SUCCESS {
            call_unsafe_wdf_function_binding!(WdfRequestComplete, request, status);
            return;
        }
    }
    let mut out_ptr: PVOID = null_mut();
    let mut out_got: usize = 0;
    if output_len > 0 {
        let status = call_unsafe_wdf_function_binding!(
            WdfRequestRetrieveOutputBuffer,
            request,
            0,
            &mut out_ptr,
            &mut out_got
        );
        if status != STATUS_SUCCESS {
            call_unsafe_wdf_function_binding!(WdfRequestComplete, request, status);
            return;
        }
    }

    let input: &[u8] = if in_got > 0 {
        core::slice::from_raw_parts(in_ptr.cast::<u8>(), in_got)
    } else {
        &[]
    };
    let output: &mut [u8] = if out_got > 0 {
        core::slice::from_raw_parts_mut(out_ptr.cast::<u8>(), out_got)
    } else {
        &mut []
    };

    let result = {
        let mut handles = shell.handles.lock().unwrap();
        let handle = handles.entry(file_key).or_insert_with(HandleCtx::default);
        let mut dev = shell.dev.lock().unwrap();
        dispatch(&mut dev, handle, shell.now_ms(), code, input, output)
    };

    let (status, info): (NTSTATUS, usize) = match result.status {
        Status::Ok => (STATUS_SUCCESS, result.bytes_written),
        Status::BadBuffer => (STATUS_INVALID_PARAMETER, 0),
        Status::UnknownCode => (STATUS_INVALID_DEVICE_REQUEST, 0),
    };
    call_unsafe_wdf_function_binding!(
        WdfRequestCompleteWithInformation,
        request,
        status,
        info as u64
    );

    // OS work strictly after request completion — queued to the effects
    // worker, never applied on this IddCx callback frame.
    queue_effects(result.effects);
}

pub unsafe extern "C" fn evt_file_create(
    _device: WDFDEVICE,
    request: WDFREQUEST,
    file_object: WDFFILEOBJECT,
) {
    // Which name is this open using? Interface opens through our control
    // symlink carry the reference string; the OS graphics stack's opens
    // of the same device object carry other (usually empty) names and
    // must pass unhindered (phase-2 lesson: they run unelevated).
    let name_ptr = call_unsafe_wdf_function_binding!(WdfFileObjectGetFileName, file_object);
    let name: &[u16] = if name_ptr.is_null() {
        &[]
    } else {
        let n = &*name_ptr;
        if n.Buffer.is_null() {
            &[]
        } else {
            core::slice::from_raw_parts(n.Buffer, (n.Length / 2) as usize)
        }
    };

    if !is_control_name(name) {
        // Not the control plane: allow, unauthorized (IOCTLs are refused).
        if let Some(shell) = Shell::try_get() {
            shell
                .handles
                .lock()
                .unwrap()
                .insert(file_object as usize, HandleCtx::default());
        }
        call_unsafe_wdf_function_binding!(WdfRequestComplete, request, STATUS_SUCCESS);
        return;
    }

    // Control-plane open: DESIGN.md §6 — SYSTEM or elevated Administrators
    // only. Refused callers fail the open (fail closed). When the token
    // CANNOT be evaluated (impersonation machinery, not policy), the open
    // is allowed but UNAUTHORIZED: every IOCTL then re-runs the same check
    // against its own caller, so a create-time evaluation quirk cannot
    // permanently brick a legitimate SYSTEM caller — and an illegitimate
    // one still cannot issue a single IOCTL.
    match authorize_request(request) {
        AuthOutcome::Authorized { how } => {
            tracelogging::write_event!(
                PROVIDER,
                "ControlOpenAuthorized",
                level(Informational),
                u32("how", &how)
            );
            if let Some(shell) = Shell::try_get() {
                shell.handles.lock().unwrap().insert(
                    file_object as usize,
                    HandleCtx { authorized: true, ..HandleCtx::default() },
                );
            }
            call_unsafe_wdf_function_binding!(WdfRequestComplete, request, STATUS_SUCCESS);
        }
        AuthOutcome::Refused => {
            tracelogging::write_event!(
                PROVIDER,
                "ControlOpenDenied",
                level(Warning),
                u32("stage", &STAGE_POLICY),
                u32("code", &0u32)
            );
            call_unsafe_wdf_function_binding!(WdfRequestComplete, request, STATUS_ACCESS_DENIED);
        }
        AuthOutcome::Unavailable { stage, code } => {
            tracelogging::write_event!(
                PROVIDER,
                "ControlOpenAuthUnavailable",
                level(Warning),
                u32("stage", &stage),
                u32("code", &code)
            );
            if let Some(shell) = Shell::try_get() {
                shell
                    .handles
                    .lock()
                    .unwrap()
                    .insert(file_object as usize, HandleCtx::default());
            }
            call_unsafe_wdf_function_binding!(WdfRequestComplete, request, STATUS_SUCCESS);
        }
    }
}

pub unsafe extern "C" fn evt_file_close(file_object: WDFFILEOBJECT) {
    if let Some(shell) = Shell::try_get() {
        shell.handles.lock().unwrap().remove(&(file_object as usize));
    }
}
