// SPDX-License-Identifier: AGPL-3.0-only
//! Generates include/luminal_vgd.h from the FFI surface. The header is
//! committed (LuminalShine's CMake includes it without running cargo);
//! this regenerates it on every build so drift is impossible to miss in
//! review.

fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        include_guard: Some("LUMINAL_VGD_H".into()),
        header: Some(
            "/* SPDX-License-Identifier: AGPL-3.0-only\n * Generated by luminal-vgd-ffi's build.rs (cbindgen) — do not edit.\n *\n * Link (MSYS2 UCRT64):\n *   cargo build -p luminal-vgd-ffi --release --target x86_64-pc-windows-gnullvm\n *   ... -lluminal_vgd_ffi -lcfgmgr32 -lws2_32 -luserenv -lntdll -lbcrypt\n */"
                .into(),
        ),
        cpp_compat: true,
        ..Default::default()
    };
    match cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
    {
        Ok(bindings) => {
            bindings.write_to_file(format!("{crate_dir}/include/luminal_vgd.h"));
        }
        // Never fail the build over header generation (e.g. during a
        // syntax-error iteration); the committed header stays.
        Err(e) => println!("cargo:warning=cbindgen skipped: {e}"),
    }
    println!("cargo:rerun-if-changed=src/lib.rs");
}
